-- Generated public staging routes. Recipient addresses remain Cloudflare-only and are intentionally NULL.
INSERT OR REPLACE INTO site_routes (site_key, brand_name, routing_status, active_client_recipient, llg_copy_recipient, sender_address, allowed_origins, phone_route_id, sms_capability, updated_at) VALUES
('austin-drain-guys','Austin Drain Guys','staging',NULL,NULL,NULL,'["https://clone-rebuild.austin-drain-guys.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('baltimore-french-drain','Baltimore French Drain','staging',NULL,NULL,NULL,'["https://clone-rebuild.baltimore-french-drain.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('charlotte-crawl-space','Charlotte Crawl Space','staging',NULL,NULL,NULL,'["https://clone-rebuild.charlotte-crawl-space.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('charlotte-precision-walls','Charlotte Precision Walls','staging',NULL,NULL,NULL,'["https://clone-rebuild.charlotte-precision-walls.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('chicago-drainage-guys','Chicago Drainage Guys','staging',NULL,NULL,NULL,'["https://clone-rebuild.chicago-drainage-guys.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('cincinnati-precision-walls','Cincinnati Precision Walls','staging',NULL,NULL,NULL,'["https://clone-rebuild.cincinnati-precision-walls.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('connecticut-drain-pros','Connecticut Drain Pros','staging',NULL,NULL,NULL,'["https://clone-rebuild.connecticut-drain-pros.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('crawlspace-cary-nc','Crawlspace Cary NC','staging',NULL,NULL,NULL,'["https://clone-rebuild.crawlspace-cary-nc.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('crawlspace-durham','Crawlspace Durham','staging',NULL,NULL,NULL,'["https://clone-rebuild.crawlspace-durham.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('crawlspace-greensboro','Crawlspace Greensboro','staging',NULL,NULL,NULL,'["https://clone-rebuild.crawlspace-greensboro.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('crawlspace-raleigh','Crawlspace Raleigh','staging',NULL,NULL,NULL,'["https://clone-rebuild.crawlspace-raleigh.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('crawlspace-wilmington','Crawlspace Wilmington','staging',NULL,NULL,NULL,'["https://clone-rebuild.crawlspace-wilmington.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('dallas-drain-guys','Dallas Drain Guys','staging',NULL,NULL,NULL,'["https://clone-rebuild.dallas-drain-guys.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('greensboro-drain-guys','Greensboro Drain Guys','staging',NULL,NULL,NULL,'["https://clone-rebuild.greensboro-drain-guys.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('jackson-french-drain','Jackson French Drain','staging',NULL,NULL,NULL,'["https://clone-rebuild.jackson-french-drain.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('little-rock-french-drain','Little Rock French Drain','staging',NULL,NULL,NULL,'["https://clone-rebuild.little-rock-french-drain.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('little-rock-precision-walls','Little Rock Precision Walls','staging',NULL,NULL,NULL,'["https://clone-rebuild.little-rock-precision-walls.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('louisville-precision-walls','Louisville Precision Walls','staging',NULL,NULL,NULL,'["https://clone-rebuild.louisville-precision-walls.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('morgantown-fence-pros','Morgantown Fence Pros','staging',NULL,NULL,NULL,'["https://clone-rebuild.morgantown-fence-pros.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('naples-pool-pros','Naples Pool Pros','staging',NULL,NULL,NULL,'["https://clone-rebuild.naples-pool-pros.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('nashville-crawlspace','Nashville Crawlspace','staging',NULL,NULL,NULL,'["https://clone-rebuild.nashville-crawlspace.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('nashville-backyards','Nashville Backyards','staging',NULL,NULL,NULL,'["https://clone-rebuild.nashville-backyards.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('new-orleans-french-drain','New Orleans French Drain','staging',NULL,NULL,NULL,'["https://clone-rebuild.new-orleans-french-drain.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('pgh-painting-pros','PGH Painting Pros','staging',NULL,NULL,NULL,'["https://clone-rebuild.pgh-painting-pros.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('pgh-pool-service','PGH Pool Service','staging',NULL,NULL,NULL,'["https://clone-rebuild.pgh-pool-service.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('pittsburgh-french-drain','Pittsburgh French Drain','staging',NULL,NULL,NULL,'["https://clone-rebuild.pittsburgh-french-drain-site.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('salt-lake-city-precision-walls','Salt Lake City Precision Walls','staging',NULL,NULL,NULL,'["https://clone-rebuild.salt-lake-city-precision-walls.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('tulsa-drain-pros','Tulsa Drain Pros','staging',NULL,NULL,NULL,'["https://clone-rebuild.tulsa-drain-pros.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP),
('ws-crawl-space','WS Crawl Space','staging',NULL,NULL,NULL,'["https://clone-rebuild.ws-crawl-space.pages.dev","http://localhost:4173"]',NULL,'disabled',CURRENT_TIMESTAMP);
