-- Supabase-first provider ingestion, channel readiness, integration runs, and delivery circuit breaker.

create table if not exists public.portfolio_controls (
  control_key text primary key,
  delivery_enabled boolean not null default false,
  capture_started_at timestamptz not null default now(),
  notes text,
  updated_at timestamptz not null default now()
);

insert into public.portfolio_controls (control_key, delivery_enabled, notes)
values ('lead_operations', false, 'All portfolio leads remain internal, unassigned, non-billable, and undelivered.')
on conflict (control_key) do update
set delivery_enabled = false,
    notes = excluded.notes,
    updated_at = now();

create table if not exists public.property_channel_readiness (
  property_id bigint not null references public.properties(id) on delete cascade,
  channel text not null check (channel in ('website_form','phone_call','google_ads','meta_ads')),
  status text not null default 'blocked' check (status in ('test','ready','live','blocked')),
  blockers text[] not null default array[]::text[],
  mapping_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(mapping_evidence) = 'object'),
  last_tested_at timestamptz,
  last_verified_at timestamptz,
  verified_by uuid references auth.users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (property_id, channel)
);

create index if not exists property_channel_readiness_status_channel_idx
  on public.property_channel_readiness(status, channel, property_id);
create index if not exists property_channel_readiness_blocked_idx
  on public.property_channel_readiness(property_id, channel)
  where status = 'blocked';

alter table public.source_mappings add column if not exists mapping_status text not null default 'verified';
alter table public.source_mappings add column if not exists mapping_confidence numeric(4,3) not null default 1.000;
alter table public.source_mappings add column if not exists verified_at timestamptz;
alter table public.source_mappings add column if not exists verified_by uuid references auth.users(id) on delete set null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'source_mappings_mapping_status_check'
      and conrelid = 'public.source_mappings'::regclass
  ) then
    alter table public.source_mappings add constraint source_mappings_mapping_status_check
      check (mapping_status in ('verified','unverified','blocked'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'source_mappings_mapping_confidence_check'
      and conrelid = 'public.source_mappings'::regclass
  ) then
    alter table public.source_mappings add constraint source_mappings_mapping_confidence_check
      check (mapping_confidence between 0 and 1);
  end if;
end $$;

create index if not exists source_mappings_active_exact_lookup_idx
  on public.source_mappings(platform, external_type, external_id, property_id)
  where is_active and mapping_status = 'verified';

create table if not exists public.integration_sync_runs (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  sync_kind text not null default 'scheduled',
  status text not null default 'running' check (status in ('running','succeeded','partial','failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  records_received integer not null default 0 check (records_received >= 0),
  records_inserted integer not null default 0 check (records_inserted >= 0),
  records_updated integer not null default 0 check (records_updated >= 0),
  records_rejected integer not null default 0 check (records_rejected >= 0),
  records_unmapped integer not null default 0 check (records_unmapped >= 0),
  failure_details jsonb not null default '[]'::jsonb check (jsonb_typeof(failure_details) = 'array'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists integration_sync_runs_provider_started_idx
  on public.integration_sync_runs(provider, started_at desc);
create index if not exists integration_sync_runs_failed_idx
  on public.integration_sync_runs(started_at desc)
  where status in ('partial','failed');

create table if not exists public.normalized_provider_events (
  id bigint generated by default as identity primary key,
  event_uid text not null unique,
  idempotency_key text not null unique,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  property_id bigint references public.properties(id) on delete set null,
  mapping_status text not null default 'unmapped' check (mapping_status in ('matched','unmapped','ambiguous','blocked')),
  mapping_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(mapping_evidence) = 'object'),
  acquisition_source text not null default 'unknown',
  acquisition_confidence text not null default 'unknown' check (acquisition_confidence in ('confirmed','explicit','inferred','ambiguous','unverified','unknown')),
  conversion_channel text not null check (conversion_channel in ('website_form','phone_call','sms','email','other')),
  campaign_id text,
  campaign_name text,
  ad_group_id text,
  ad_group_name text,
  ad_id text,
  ad_name text,
  keyword text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  gclid text,
  gbraid text,
  wbraid text,
  fbclid text,
  landing_page_url text,
  referrer_url text,
  visitor_id text,
  session_id text,
  contact jsonb not null default '{}'::jsonb check (jsonb_typeof(contact) = 'object'),
  consent jsonb not null default '{}'::jsonb check (jsonb_typeof(consent) = 'object'),
  service jsonb not null default '{}'::jsonb check (jsonb_typeof(service) = 'object'),
  qualification jsonb not null default '{}'::jsonb check (jsonb_typeof(qualification) = 'object'),
  occurred_at timestamptz,
  received_at timestamptz not null default now(),
  test_mode boolean not null default true,
  processing_status text not null default 'received' check (processing_status in ('received','processed','duplicate','unmapped','blocked','rejected','failed')),
  raw_webhook_event_id bigint references public.webhook_events(id) on delete set null,
  lead_id bigint references public.leads(id) on delete set null,
  correlation_ids jsonb not null default '{}'::jsonb check (jsonb_typeof(correlation_ids) = 'object'),
  error_message text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_event_id)
);

create index if not exists normalized_provider_events_property_received_idx
  on public.normalized_provider_events(property_id, received_at desc);
create index if not exists normalized_provider_events_provider_received_idx
  on public.normalized_provider_events(provider, received_at desc);
create index if not exists normalized_provider_events_unmapped_idx
  on public.normalized_provider_events(received_at desc)
  where mapping_status in ('unmapped','ambiguous','blocked') or processing_status in ('rejected','failed');
create index if not exists normalized_provider_events_lead_id_idx
  on public.normalized_provider_events(lead_id) where lead_id is not null;

alter table public.property_channel_readiness enable row level security;
alter table public.integration_sync_runs enable row level security;
alter table public.normalized_provider_events enable row level security;
alter table public.portfolio_controls enable row level security;

revoke all on public.property_channel_readiness from anon, authenticated;
revoke all on public.integration_sync_runs from anon, authenticated;
revoke all on public.normalized_provider_events from anon, authenticated;
revoke all on public.portfolio_controls from anon, authenticated;

create or replace function private.assert_portfolio_ingest_token(p_token text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_expected_hash text;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'fillout_ingest';
  if v_expected_hash is null
    or extensions.digest(coalesce(p_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;
end;
$$;

revoke all on function private.assert_portfolio_ingest_token(text) from public, anon, authenticated;

create or replace function private.enforce_internal_lead_safety()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_delivery_enabled boolean := false;
begin
  select delivery_enabled into v_delivery_enabled
  from public.portfolio_controls where control_key = 'lead_operations';
  if not coalesce(v_delivery_enabled, false) and tg_op = 'INSERT' then
    new.assigned_client_id := null;
    new.is_billable := false;
    new.status := 'validating';
    new.qualification_status := 'needs_review';
    new.routed_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists leads_internal_safety_before_insert on public.leads;
create trigger leads_internal_safety_before_insert
before insert on public.leads
for each row execute function private.enforce_internal_lead_safety();

create or replace function private.block_disabled_delivery()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_delivery_enabled boolean := false;
begin
  select delivery_enabled into v_delivery_enabled
  from public.portfolio_controls where control_key = 'lead_operations';
  if not coalesce(v_delivery_enabled, false) then
    raise exception 'lead delivery is disabled by portfolio circuit breaker' using errcode = '55000';
  end if;
  return new;
end;
$$;

drop trigger if exists lead_deliveries_circuit_breaker on public.lead_deliveries;
create trigger lead_deliveries_circuit_breaker
before insert on public.lead_deliveries
for each row execute function private.block_disabled_delivery();

create or replace function public.ingest_provider_event(
  p_event jsonb,
  p_payload jsonb,
  p_request_id text,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_provider text := lower(nullif(btrim(p_event->>'provider'), ''));
  v_provider_event_id text := nullif(btrim(p_event->>'provider_event_id'), '');
  v_event_type text := coalesce(nullif(btrim(p_event->>'event_type'), ''), 'conversion');
  v_idempotency_key text := coalesce(nullif(btrim(p_event->>'idempotency_key'), ''), v_provider || ':' || v_provider_event_id);
  v_event_uid text;
  v_property_key text := nullif(btrim(p_event->>'property_key'), '');
  v_property_id bigint;
  v_mapping_count integer := 0;
  v_mapping_status text := 'unmapped';
  v_mapping_evidence jsonb := '{}'::jsonb;
  v_channel text := lower(coalesce(nullif(p_event->>'conversion_channel',''), 'other'));
  v_gate_channel text;
  v_gate_status text;
  v_acquisition text := lower(coalesce(nullif(p_event->>'acquisition_source',''), 'unknown'));
  v_confidence text := lower(coalesce(nullif(p_event->>'acquisition_confidence',''), 'unknown'));
  v_test_mode boolean := coalesce((p_event->>'test_mode')::boolean, true);
  v_webhook_id bigint;
  v_normalized_id bigint;
  v_lead_id bigint;
  v_lead_public_id uuid;
  v_duplicate boolean := false;
  v_market_id bigint;
  v_service_id bigint;
  v_provider_id bigint;
  v_occurred_at timestamptz := coalesce(nullif(p_event->>'occurred_at','')::timestamptz, now());
  v_contact jsonb := coalesce(p_event->'contact', '{}'::jsonb);
  v_consent jsonb := coalesce(p_event->'consent', '{}'::jsonb);
  v_service jsonb := coalesce(p_event->'service', '{}'::jsonb);
  v_attribution jsonb := coalesce(p_event->'attribution', '{}'::jsonb);
  v_correlation jsonb := coalesce(p_event->'correlation_ids', '{}'::jsonb);
begin
  perform private.assert_portfolio_ingest_token(p_ingest_token);
  if jsonb_typeof(p_event) <> 'object' or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'event and payload must be objects' using errcode = '22023';
  end if;
  if v_provider is null or v_provider_event_id is null then
    raise exception 'provider and provider_event_id are required' using errcode = '22023';
  end if;
  if v_channel not in ('website_form','phone_call','sms','email','other') then
    raise exception 'invalid conversion channel' using errcode = '22023';
  end if;
  if v_confidence not in ('confirmed','explicit','inferred','ambiguous','unverified','unknown') then
    v_confidence := 'unknown';
  end if;
  v_event_uid := v_provider || ':' || v_provider_event_id;

  insert into public.webhook_events(source_system,event_id,event_type,status,payload,received_at,attempt_count)
  values (v_provider,v_provider_event_id,v_event_type,'processing',p_payload,now(),1)
  on conflict (source_system,event_id) do update
  set payload=excluded.payload,status='processing',error_message=null,
      attempt_count=public.webhook_events.attempt_count+1
  returning id into v_webhook_id;

  if v_property_key is not null then
    select id into v_property_id from public.properties where property_key = v_property_key;
    if v_property_id is not null then
      v_mapping_status := 'matched';
      v_mapping_evidence := jsonb_build_object('method','property_key','property_key',v_property_key);
    end if;
  end if;

  if v_property_id is null and jsonb_typeof(p_event->'mapping_keys') = 'array' then
    with supplied as (
      select lower(k->>'platform') platform, lower(k->>'external_type') external_type, k->>'external_id' external_id
      from jsonb_array_elements(p_event->'mapping_keys') k
      where nullif(k->>'platform','') is not null and nullif(k->>'external_type','') is not null and nullif(k->>'external_id','') is not null
    ), matches as (
      select distinct sm.property_id, sm.platform, sm.external_type, sm.external_id
      from supplied s join public.source_mappings sm
        on lower(sm.platform)=s.platform and lower(sm.external_type)=s.external_type and sm.external_id=s.external_id
      where sm.is_active and sm.mapping_status='verified' and sm.property_id is not null
    )
    select count(distinct property_id), min(property_id),
      jsonb_build_object('method','source_mappings','matches',coalesce(jsonb_agg(jsonb_build_object('platform',platform,'external_type',external_type,'external_id',external_id)), '[]'::jsonb))
    into v_mapping_count, v_property_id, v_mapping_evidence from matches;
    if v_mapping_count = 1 then v_mapping_status := 'matched';
    elsif v_mapping_count > 1 then v_property_id := null; v_mapping_status := 'ambiguous';
    else v_property_id := null; v_mapping_status := 'unmapped';
    end if;
  end if;

  if v_property_id is not null then
    select p.market_id, coalesce(pc.test_mode,true) into v_market_id, v_test_mode
    from public.properties p left join public.property_configurations pc on pc.property_id=p.id
    where p.id=v_property_id;
    v_test_mode := coalesce((p_event->>'test_mode')::boolean, v_test_mode, true);
    if v_channel in ('website_form','phone_call') then v_gate_channel := v_channel;
    elsif v_acquisition='google_ads' then v_gate_channel := 'google_ads';
    elsif v_acquisition='meta_ads' then v_gate_channel := 'meta_ads';
    else v_gate_channel := v_channel; end if;
    select status into v_gate_status
    from public.property_channel_readiness
    where property_id=v_property_id and channel=v_gate_channel;
    if not v_test_mode and coalesce(v_gate_status,'blocked') <> 'live' then
      v_mapping_status := 'blocked';
    end if;
  end if;

  if v_acquisition='google_ads'
    and coalesce(v_attribution->>'gclid','')=''
    and coalesce(v_attribution->>'gbraid','')=''
    and coalesce(v_attribution->>'wbraid','')=''
    and not (
      lower(coalesce(v_attribution->>'utm_source','')) in ('google','adwords')
      and lower(coalesce(v_attribution->>'utm_medium','')) in ('cpc','ppc','paid','paid_search')
    ) then
    v_acquisition := 'google_unverified';
    v_confidence := 'unverified';
  end if;

  insert into public.normalized_provider_events(
    event_uid,idempotency_key,provider,provider_event_id,event_type,property_id,mapping_status,mapping_evidence,
    acquisition_source,acquisition_confidence,conversion_channel,campaign_id,campaign_name,ad_group_id,ad_group_name,
    ad_id,ad_name,keyword,utm_source,utm_medium,utm_campaign,utm_content,utm_term,gclid,gbraid,wbraid,fbclid,
    landing_page_url,referrer_url,visitor_id,session_id,contact,consent,service,qualification,occurred_at,test_mode,
    processing_status,raw_webhook_event_id,correlation_ids,metadata,updated_at
  ) values (
    v_event_uid,v_idempotency_key,v_provider,v_provider_event_id,v_event_type,v_property_id,v_mapping_status,v_mapping_evidence,
    v_acquisition,v_confidence,v_channel,nullif(v_attribution->>'campaign_id',''),nullif(v_attribution->>'campaign_name',''),
    nullif(v_attribution->>'ad_group_id',''),nullif(v_attribution->>'ad_group_name',''),nullif(v_attribution->>'ad_id',''),
    nullif(v_attribution->>'ad_name',''),nullif(v_attribution->>'keyword',''),nullif(v_attribution->>'utm_source',''),
    nullif(v_attribution->>'utm_medium',''),nullif(v_attribution->>'utm_campaign',''),nullif(v_attribution->>'utm_content',''),
    nullif(v_attribution->>'utm_term',''),nullif(v_attribution->>'gclid',''),nullif(v_attribution->>'gbraid',''),
    nullif(v_attribution->>'wbraid',''),nullif(v_attribution->>'fbclid',''),nullif(v_attribution->>'landing_page_url',''),
    nullif(v_attribution->>'referrer_url',''),nullif(v_attribution->>'visitor_id',''),nullif(v_attribution->>'session_id',''),
    v_contact,v_consent,v_service,coalesce(p_event->'qualification','{}'::jsonb),v_occurred_at,v_test_mode,
    case when v_mapping_status='matched' then 'received' when v_mapping_status='blocked' then 'blocked' else 'unmapped' end,v_webhook_id,v_correlation,
    jsonb_build_object('request_id',p_request_id,'contract_version','2026-08-06'),now()
  )
  on conflict (provider,provider_event_id) do update
  set mapping_status=excluded.mapping_status,mapping_evidence=excluded.mapping_evidence,property_id=coalesce(excluded.property_id,public.normalized_provider_events.property_id),
      contact=excluded.contact,consent=excluded.consent,service=excluded.service,qualification=excluded.qualification,
      correlation_ids=public.normalized_provider_events.correlation_ids||excluded.correlation_ids,updated_at=now()
  returning id, lead_id into v_normalized_id, v_lead_id;

  if v_lead_id is not null then
    v_duplicate := true;
    update public.normalized_provider_events set processing_status='duplicate',updated_at=now() where id=v_normalized_id;
    update public.webhook_events set status='processed',processed_at=now() where id=v_webhook_id;
    return jsonb_build_object('accepted',true,'duplicate',true,'lead_id',v_lead_id,'property_id',v_property_id,'mapping_status',v_mapping_status,'test_mode',v_test_mode);
  end if;
  if v_mapping_status <> 'matched' then
    update public.webhook_events set status='processed',processed_at=now(),error_message='retained:'||v_mapping_status where id=v_webhook_id;
    return jsonb_build_object('accepted',false,'duplicate',false,'lead_id',null,'property_id',v_property_id,'mapping_status',v_mapping_status,'test_mode',v_test_mode);
  end if;

  if nullif(v_service->>'service_id','') ~ '^[0-9]+$' then v_service_id := (v_service->>'service_id')::bigint; end if;
  if v_service_id is null then
    select ps.service_id into v_service_id from public.property_services ps
    where ps.property_id=v_property_id and ps.is_active and ps.accepting_leads
    order by ps.is_primary desc,ps.sort_order,ps.service_id limit 1;
  end if;
  select id into v_lead_id from public.leads where ingestion_key=v_idempotency_key;
  if v_lead_id is null then
    insert into public.leads(
      ingestion_key,source_system,source_record_id,source_event_id,property_id,market_id,service_id,received_at,occurred_at,
      first_name,last_name,full_name,phone,normalized_phone,email,normalized_email,address_line_1,address_line_2,city,state_region,postal_code,
      lead_source,source_category,communication_channel,conversion_source,utm_source,utm_medium,utm_campaign,utm_content,utm_term,
      campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,keyword,gclid,gbraid,wbraid,fbclid,landing_page_url,referrer_url,
      visitor_id,session_id,fillout_submission_id,callrail_call_id,status,qualification_status,is_billable,consent_to_contact,consent_text,metadata
    ) values (
      v_idempotency_key,v_provider,v_provider_event_id,v_webhook_id,v_property_id,v_market_id,v_service_id,now(),v_occurred_at,
      nullif(v_contact->>'first_name',''),nullif(v_contact->>'last_name',''),nullif(v_contact->>'full_name',''),
      nullif(v_contact->>'phone',''),nullif(v_contact->>'normalized_phone',''),nullif(lower(v_contact->>'email'),''),nullif(lower(v_contact->>'normalized_email'),''),
      nullif(v_contact->>'address_line_1',''),nullif(v_contact->>'address_line_2',''),nullif(v_contact->>'city',''),nullif(v_contact->>'state_region',''),nullif(v_contact->>'postal_code',''),
      v_acquisition,v_acquisition,v_channel,v_provider,nullif(v_attribution->>'utm_source',''),nullif(v_attribution->>'utm_medium',''),
      nullif(v_attribution->>'utm_campaign',''),nullif(v_attribution->>'utm_content',''),nullif(v_attribution->>'utm_term',''),
      nullif(v_attribution->>'campaign_id',''),nullif(v_attribution->>'campaign_name',''),nullif(v_attribution->>'ad_group_id',''),
      nullif(v_attribution->>'ad_group_name',''),nullif(v_attribution->>'ad_id',''),nullif(v_attribution->>'ad_name',''),nullif(v_attribution->>'keyword',''),
      nullif(v_attribution->>'gclid',''),nullif(v_attribution->>'gbraid',''),nullif(v_attribution->>'wbraid',''),nullif(v_attribution->>'fbclid',''),
      nullif(v_attribution->>'landing_page_url',''),nullif(v_attribution->>'referrer_url',''),nullif(v_attribution->>'visitor_id',''),nullif(v_attribution->>'session_id',''),
      case when v_provider='fillout' then v_provider_event_id else null end,case when v_provider='callrail' then v_provider_event_id else null end,
      'validating','needs_review',false,coalesce((v_consent->>'granted')::boolean,false),nullif(v_consent->>'text',''),
      jsonb_build_object('test_mode',v_test_mode,'supabase_first_capture',true,'normalized_provider_event_id',v_normalized_id,
        'site_attribution_confidence','direct','acquisition_confidence',v_confidence,'mapping_evidence',v_mapping_evidence,
        'request_id',p_request_id,'correlation_ids',v_correlation,'qualification',coalesce(p_event->'qualification','{}'::jsonb))
    ) returning id,public_id into v_lead_id,v_lead_public_id;
  else
    v_duplicate := true;
    select public_id into v_lead_public_id from public.leads where id=v_lead_id;
  end if;

  select id into v_provider_id from public.integration_providers where provider_key=case when v_provider='meta_lead_ads' then 'meta' else v_provider end;
  insert into public.lead_interactions(lead_id,property_id,provider_id,source_event_id,conversation_id,interaction_type,channel,direction,status,summary,content,occurred_at,metadata)
  values (v_lead_id,v_property_id,v_provider_id,v_provider_event_id,nullif(v_correlation->>'conversation_id',''),
    case when v_channel='phone_call' then 'call' else 'form_submission' end,v_channel,'inbound','received',
    nullif(p_event->>'summary',''),nullif(p_event->>'message',''),v_occurred_at,
    jsonb_build_object('normalized_provider_event_id',v_normalized_id,'test_mode',v_test_mode,'acquisition_source',v_acquisition))
  on conflict do nothing;

  insert into public.lead_attribution_touches(lead_id,touch_order,touch_type,occurred_at,source,medium,campaign,campaign_id,ad_group_id,ad_id,keyword,landing_page_url,referrer_url,gclid,gbraid,wbraid,fbclid,visitor_id,session_id,metadata)
  values (v_lead_id,1,'last_touch',v_occurred_at,v_acquisition,nullif(v_attribution->>'utm_medium',''),nullif(v_attribution->>'utm_campaign',''),
    nullif(v_attribution->>'campaign_id',''),nullif(v_attribution->>'ad_group_id',''),nullif(v_attribution->>'ad_id',''),nullif(v_attribution->>'keyword',''),
    nullif(v_attribution->>'landing_page_url',''),nullif(v_attribution->>'referrer_url',''),nullif(v_attribution->>'gclid',''),nullif(v_attribution->>'gbraid',''),
    nullif(v_attribution->>'wbraid',''),nullif(v_attribution->>'fbclid',''),nullif(v_attribution->>'visitor_id',''),nullif(v_attribution->>'session_id',''),
    jsonb_build_object('confidence',v_confidence,'normalized_provider_event_id',v_normalized_id))
  on conflict (lead_id,touch_order) do nothing;

  update public.normalized_provider_events set lead_id=v_lead_id,processing_status=case when v_duplicate then 'duplicate' else 'processed' end,updated_at=now() where id=v_normalized_id;
  update public.webhook_events set status='processed',processed_at=now() where id=v_webhook_id;
  update public.property_channel_readiness set last_tested_at=case when v_test_mode then now() else last_tested_at end,updated_at=now()
  where property_id=v_property_id and channel in (v_channel,case when v_acquisition in ('google_ads','meta_ads') then v_acquisition else v_channel end);
  return jsonb_build_object('accepted',true,'duplicate',v_duplicate,'lead_id',v_lead_id,'lead_public_id',v_lead_public_id,
    'property_id',v_property_id,'mapping_status',v_mapping_status,'test_mode',v_test_mode,'normalized_event_id',v_normalized_id);
exception when others then
  if v_webhook_id is not null then update public.webhook_events set status='failed',error_message=sqlerrm where id=v_webhook_id; end if;
  if v_normalized_id is not null then update public.normalized_provider_events set processing_status='failed',error_message=sqlerrm,updated_at=now() where id=v_normalized_id; end if;
  raise;
end;
$$;

revoke all on function public.ingest_provider_event(jsonb,jsonb,text,text) from public;
grant execute on function public.ingest_provider_event(jsonb,jsonb,text,text) to anon, service_role;

create or replace function public.upsert_portfolio_ad_metric(p_metric jsonb,p_ingest_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_property_id bigint;
  v_mapping_count integer;
  v_id bigint;
  v_inserted boolean;
begin
  perform private.assert_portfolio_ingest_token(p_ingest_token);
  if jsonb_typeof(p_metric) <> 'object' then raise exception 'metric must be an object' using errcode='22023'; end if;
  with keys as (
    select lower(k->>'platform') platform,lower(k->>'external_type') external_type,k->>'external_id' external_id
    from jsonb_array_elements(coalesce(p_metric->'mapping_keys','[]'::jsonb)) k
  ), matches as (
    select distinct sm.property_id from keys k join public.source_mappings sm
      on lower(sm.platform)=k.platform and lower(sm.external_type)=k.external_type and sm.external_id=k.external_id
    where sm.is_active and sm.mapping_status='verified' and sm.property_id is not null
  ) select count(*),min(property_id) into v_mapping_count,v_property_id from matches;
  if v_mapping_count <> 1 then v_property_id := null; end if;
  select id into v_id from public.daily_ad_metrics
  where metric_date=(p_metric->>'metric_date')::date and platform=p_metric->>'platform' and account_id=p_metric->>'account_id'
    and campaign_id=p_metric->>'campaign_id' and coalesce(ad_group_id,'')=coalesce(p_metric->>'ad_group_id','')
    and coalesce(ad_id,'')=coalesce(p_metric->>'ad_id','') and coalesce(property_id,0)=coalesce(v_property_id,0);
  v_inserted := v_id is null;
  insert into public.daily_ad_metrics(metric_date,platform,account_id,account_name,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,
    client_id,property_id,impressions,clicks,spend,conversions,conversion_value,currency_code,metadata,imported_at)
  values ((p_metric->>'metric_date')::date,p_metric->>'platform',p_metric->>'account_id',nullif(p_metric->>'account_name',''),p_metric->>'campaign_id',
    nullif(p_metric->>'campaign_name',''),nullif(p_metric->>'ad_group_id',''),nullif(p_metric->>'ad_group_name',''),nullif(p_metric->>'ad_id',''),nullif(p_metric->>'ad_name',''),
    null,v_property_id,coalesce((p_metric->>'impressions')::bigint,0),coalesce((p_metric->>'clicks')::bigint,0),coalesce((p_metric->>'spend')::numeric,0),
    coalesce((p_metric->>'conversions')::numeric,0),coalesce((p_metric->>'conversion_value')::numeric,0),coalesce(nullif(p_metric->>'currency_code',''),'USD'),
    jsonb_build_object('mapping_status',case when v_property_id is null then 'unmapped' else 'matched' end,'mapping_keys',coalesce(p_metric->'mapping_keys','[]'::jsonb)),now())
  on conflict (metric_date,platform,account_id,campaign_id,(coalesce(ad_group_id,'')),(coalesce(ad_id,'')),(coalesce(property_id,0))) do update
  set account_name=excluded.account_name,campaign_name=excluded.campaign_name,ad_group_name=excluded.ad_group_name,ad_name=excluded.ad_name,
      impressions=excluded.impressions,clicks=excluded.clicks,spend=excluded.spend,conversions=excluded.conversions,
      conversion_value=excluded.conversion_value,currency_code=excluded.currency_code,metadata=excluded.metadata,imported_at=now()
  returning id into v_id;
  return jsonb_build_object('id',v_id,'inserted',v_inserted,'property_id',v_property_id,'unmapped',v_property_id is null);
end;
$$;

revoke all on function public.upsert_portfolio_ad_metric(jsonb,text) from public;
grant execute on function public.upsert_portfolio_ad_metric(jsonb,text) to anon, service_role;

create or replace function public.record_integration_sync_run(p_run jsonb,p_ingest_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare v_id uuid; v_row public.integration_sync_runs;
begin
  perform private.assert_portfolio_ingest_token(p_ingest_token);
  v_id := nullif(p_run->>'id','')::uuid;
  if v_id is null then v_id := gen_random_uuid(); end if;
  insert into public.integration_sync_runs(id,provider,sync_kind,status,started_at,finished_at,records_received,records_inserted,records_updated,records_rejected,records_unmapped,failure_details,metadata)
  values (v_id,p_run->>'provider',coalesce(nullif(p_run->>'sync_kind',''),'scheduled'),coalesce(nullif(p_run->>'status',''),'running'),
    coalesce(nullif(p_run->>'started_at','')::timestamptz,now()),nullif(p_run->>'finished_at','')::timestamptz,
    coalesce((p_run->>'records_received')::integer,0),coalesce((p_run->>'records_inserted')::integer,0),coalesce((p_run->>'records_updated')::integer,0),
    coalesce((p_run->>'records_rejected')::integer,0),coalesce((p_run->>'records_unmapped')::integer,0),
    coalesce(p_run->'failure_details','[]'::jsonb),coalesce(p_run->'metadata','{}'::jsonb))
  on conflict (id) do update set status=excluded.status,finished_at=excluded.finished_at,records_received=excluded.records_received,
    records_inserted=excluded.records_inserted,records_updated=excluded.records_updated,records_rejected=excluded.records_rejected,
    records_unmapped=excluded.records_unmapped,failure_details=excluded.failure_details,metadata=public.integration_sync_runs.metadata||excluded.metadata
  returning * into v_row;
  return to_jsonb(v_row);
end;
$$;

revoke all on function public.record_integration_sync_run(jsonb,text) from public;
grant execute on function public.record_integration_sync_run(jsonb,text) to anon, service_role;

create or replace function public.prepare_bland_call_correlation(p_payload jsonb,p_ingest_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare v_callrail_id text; v_phone text; v_started timestamptz; v_lead public.leads; v_result jsonb := p_payload;
begin
  perform private.assert_portfolio_ingest_token(p_ingest_token);
  v_callrail_id := coalesce(nullif(p_payload->>'callrail_call_id',''),nullif(p_payload#>>'{metadata,callrail_call_id}',''),nullif(p_payload#>>'{variables,callrail_call_id}',''));
  v_phone := private.normalize_e164(coalesce(p_payload->>'from',p_payload->>'phone_number',p_payload#>>'{variables,callback_number}'));
  v_started := coalesce(nullif(p_payload->>'started_at','')::timestamptz,nullif(p_payload->>'created_at','')::timestamptz,now());
  if v_callrail_id is not null then select * into v_lead from public.leads where callrail_call_id=v_callrail_id order by received_at desc limit 1; end if;
  if v_lead.id is null and v_phone is not null then
    select * into v_lead from public.leads
    where source_system='callrail' and normalized_phone=v_phone and occurred_at between v_started-interval '30 minutes' and v_started+interval '30 minutes'
    order by abs(extract(epoch from (occurred_at-v_started))) limit 1;
  end if;
  if v_lead.id is not null then
    v_result := jsonb_set(v_result,'{metadata}',coalesce(v_result->'metadata','{}'::jsonb)||jsonb_build_object(
      'lead_public_id',v_lead.public_id,'lead_id',v_lead.id,'callrail_call_id',v_lead.callrail_call_id,'correlation_method',case when v_callrail_id is not null then 'callrail_call_id' else 'phone_time_window' end),true);
  end if;
  return v_result;
end;
$$;

revoke all on function public.prepare_bland_call_correlation(jsonb,text) from public;
grant execute on function public.prepare_bland_call_correlation(jsonb,text) to anon, service_role;

comment on table public.normalized_provider_events is 'Canonical, replayable provider event contract. Unmapped and rejected events are retained for review.';
comment on table public.property_channel_readiness is 'Independent per-property capture readiness; blocked/untracked is distinct from zero leads.';
comment on table public.portfolio_controls is 'Operational circuit breakers. Delivery remains false until separately authorized.';
