create table if not exists private.fillout_webhook_inbox (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  form_id text not null,
  payload jsonb not null,
  status text not null default 'received'
    check (status in ('received', 'processed', 'rejected')),
  error_message text,
  received_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(payload) = 'object')
);

create index if not exists fillout_webhook_inbox_received_at_idx
  on private.fillout_webhook_inbox (received_at desc);

create or replace function public.record_fillout_webhook_attempt(
  p_form_id text,
  p_payload jsonb,
  p_request_id text,
  p_ingest_token text,
  p_status text default 'received',
  p_error_message text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_inbox_id bigint;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'fillout_ingest';

  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;

  if jsonb_typeof(p_payload) <> 'object' then
    raise exception 'invalid webhook payload' using errcode = '22023';
  end if;

  if p_status not in ('received', 'processed', 'rejected') then
    raise exception 'invalid webhook status' using errcode = '22023';
  end if;

  insert into private.fillout_webhook_inbox (
    request_id, form_id, payload, status, error_message
  ) values (
    p_request_id, p_form_id, p_payload, p_status, nullif(p_error_message, '')
  )
  on conflict (request_id) do update
  set status = excluded.status,
      error_message = excluded.error_message,
      updated_at = now()
  returning id into v_inbox_id;

  return v_inbox_id;
end;
$$;

revoke all on function public.record_fillout_webhook_attempt(text, jsonb, text, text, text, text) from public;
grant execute on function public.record_fillout_webhook_attempt(text, jsonb, text, text, text, text) to anon, service_role;

comment on table private.fillout_webhook_inbox
is 'Authenticated raw Fillout webhook inbox retained before normalization for audit and replay.';

comment on function public.record_fillout_webhook_attempt(text, jsonb, text, text, text, text)
is 'Authenticates, records, and updates raw Fillout webhook delivery attempts.';
