create table public.sms_qualification_flows (
  property_id bigint primary key references public.properties(id) on delete cascade,
  sending_provider_id bigint not null references public.integration_providers(id),
  sending_phone_e164 text not null check (sending_phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  status text not null default 'draft'
    check (status in ('draft', 'testing', 'active', 'paused', 'retired')),
  intro_message text not null,
  questions jsonb not null check (jsonb_typeof(questions) = 'array'),
  completion_message text not null,
  settings jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sms_qualification_sessions (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id),
  lead_id bigint references public.leads(id),
  contact_phone_e164 text not null check (contact_phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  sending_provider_id bigint not null references public.integration_providers(id),
  sending_phone_e164 text not null check (sending_phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  status text not null default 'active'
    check (status in ('active', 'completed', 'opted_out', 'paused', 'expired')),
  current_step integer not null default 0 check (current_step >= 0),
  answers jsonb not null default '{}'::jsonb check (jsonb_typeof(answers) = 'object'),
  last_inbound_provider_id bigint references public.integration_providers(id),
  last_inbound_message_id text,
  last_reply_text text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  last_activity_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index sms_qualification_sessions_one_active_idx
  on public.sms_qualification_sessions (property_id, contact_phone_e164)
  where status = 'active';
create index sms_qualification_sessions_lead_idx
  on public.sms_qualification_sessions (lead_id, last_activity_at desc)
  where lead_id is not null;
create index sms_qualification_sessions_contact_idx
  on public.sms_qualification_sessions (contact_phone_e164, last_activity_at desc);

alter table public.sms_qualification_flows enable row level security;
alter table public.sms_qualification_sessions enable row level security;
revoke all on public.sms_qualification_flows from anon, authenticated;
revoke all on public.sms_qualification_sessions from anon, authenticated;

insert into public.sms_qualification_flows (
  property_id, sending_provider_id, sending_phone_e164, status,
  intro_message, questions, completion_message, settings
)
select
  p.id,
  ip.id,
  '+18337689020',
  'testing',
  'Thanks for contacting 3V San Antonio Paver Services.',
  jsonb_build_array(
    jsonb_build_object('key', 'project_type', 'prompt', 'What type of paver or concrete project do you need help with? Reply STOP to opt out.'),
    jsonb_build_object('key', 'postal_code', 'prompt', 'What ZIP code is the project located in?'),
    jsonb_build_object('key', 'timeline', 'prompt', 'When would you like the work to begin?')
  ),
  'Thanks—we have what we need. A local specialist will follow up about your quote shortly. Reply STOP to opt out.',
  jsonb_build_object(
    'pilot', 'verified-five-v1',
    'transport', 'textmagic',
    'entry_channel', 'callrail_sms',
    'shared_sender_requires_prior_outbound', true
  )
from public.properties p
join public.integration_providers ip on ip.provider_key = 'textmagic' and ip.is_active
where p.domain = '3vsanantoniopaverservices.com'
on conflict (property_id) do update
set sending_provider_id = excluded.sending_provider_id,
    sending_phone_e164 = excluded.sending_phone_e164,
    status = excluded.status,
    intro_message = excluded.intro_message,
    questions = excluded.questions,
    completion_message = excluded.completion_message,
    settings = public.sms_qualification_flows.settings || excluded.settings,
    updated_at = now();

create or replace function public.start_sms_qualification(
  p_property_key text,
  p_contact_phone text,
  p_lead_id bigint,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_property_id bigint;
  v_phone text;
  v_flow public.sms_qualification_flows%rowtype;
  v_session public.sms_qualification_sessions%rowtype;
  v_first_prompt text;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets where secret_key = 'fillout_ingest';
  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;

  v_phone := private.normalize_e164(p_contact_phone);
  if v_phone is null then
    raise exception 'invalid contact phone' using errcode = '22023';
  end if;

  select id into v_property_id
  from public.properties
  where property_key = lower(btrim(p_property_key));
  if v_property_id is null then
    raise exception 'unknown property' using errcode = '22023';
  end if;

  if p_lead_id is not null and not exists (
    select 1 from public.leads where id = p_lead_id and property_id = v_property_id
  ) then
    raise exception 'lead does not belong to property' using errcode = '22023';
  end if;

  select * into v_flow
  from public.sms_qualification_flows
  where property_id = v_property_id and status in ('testing', 'active');
  if v_flow.property_id is null then
    return jsonb_build_object('should_send', false, 'reason', 'flow_unavailable');
  end if;

  select * into v_session
  from public.sms_qualification_sessions
  where property_id = v_property_id and contact_phone_e164 = v_phone and status = 'active'
  order by id desc limit 1;

  if v_session.id is null then
    insert into public.sms_qualification_sessions (
      property_id, lead_id, contact_phone_e164, sending_provider_id,
      sending_phone_e164, metadata
    ) values (
      v_property_id, p_lead_id, v_phone, v_flow.sending_provider_id,
      v_flow.sending_phone_e164, jsonb_build_object('started_by', 'admin_or_automation')
    ) returning * into v_session;
  elsif v_session.lead_id is null and p_lead_id is not null then
    update public.sms_qualification_sessions
    set lead_id = p_lead_id, updated_at = now()
    where id = v_session.id
    returning * into v_session;
  end if;

  v_first_prompt := nullif(v_flow.questions->0->>'prompt', '');
  return jsonb_build_object(
    'should_send', v_first_prompt is not null,
    'session_id', v_session.id,
    'property_id', v_property_id,
    'lead_id', v_session.lead_id,
    'to_phone', v_phone,
    'from_phone', v_flow.sending_phone_e164,
    'message', concat_ws(' ', nullif(v_flow.intro_message, ''), v_first_prompt),
    'status', v_session.status,
    'step', v_session.current_step
  );
end;
$$;

create or replace function public.prepare_sms_qualification_reply(
  p_source_provider_key text,
  p_external_message_id text,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_source_provider_id bigint;
  v_message public.sms_messages%rowtype;
  v_flow public.sms_qualification_flows%rowtype;
  v_session public.sms_qualification_sessions%rowtype;
  v_contact text;
  v_answer_key text;
  v_next_prompt text;
  v_reply text;
  v_next_step integer;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets where secret_key = 'fillout_ingest';
  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;

  select id into v_source_provider_id
  from public.integration_providers
  where provider_key = lower(btrim(p_source_provider_key)) and is_active;
  if v_source_provider_id is null then
    raise exception 'unknown source provider' using errcode = '22023';
  end if;

  select * into v_message
  from public.sms_messages
  where provider_id = v_source_provider_id
    and external_message_id = p_external_message_id
    and direction = 'inbound';
  if v_message.id is null then
    return jsonb_build_object('should_send', false, 'reason', 'inbound_message_not_found');
  end if;

  v_contact := v_message.from_phone_e164;

  -- The TextMagic sender is shared. A reply is only attributed when this
  -- contact was first sent a property-linked TextMagic message recently.
  if v_message.property_id is null and lower(btrim(p_source_provider_key)) = 'textmagic' then
    select sm.property_id, sm.lead_id
    into v_message.property_id, v_message.lead_id
    from public.sms_messages sm
    where sm.provider_id = v_source_provider_id
      and sm.direction = 'outbound'
      and sm.to_phone_e164 = v_contact
      and sm.from_phone_e164 = v_message.to_phone_e164
      and sm.property_id is not null
      and sm.occurred_at >= now() - interval '14 days'
    order by sm.occurred_at desc, sm.id desc
    limit 1;

    if v_message.property_id is not null then
      update public.sms_messages
      set property_id = v_message.property_id,
          lead_id = coalesce(public.sms_messages.lead_id, v_message.lead_id),
          metadata = metadata || jsonb_build_object('routing_source', 'recent_textmagic_outbound'),
          updated_at = now()
      where id = v_message.id;
    end if;
  end if;

  if v_message.property_id is null or v_contact is null then
    return jsonb_build_object('should_send', false, 'reason', 'unmatched_shared_sender');
  end if;

  select * into v_flow
  from public.sms_qualification_flows
  where property_id = v_message.property_id and status in ('testing', 'active');
  if v_flow.property_id is null then
    return jsonb_build_object('should_send', false, 'reason', 'flow_unavailable');
  end if;

  select * into v_session
  from public.sms_qualification_sessions
  where property_id = v_message.property_id
    and contact_phone_e164 = v_contact
    and status = 'active'
  order by id desc limit 1;

  if upper(btrim(coalesce(v_message.message_body, ''))) ~ '^(STOP|STOPALL|UNSUBSCRIBE|CANCEL|END|QUIT)$' then
    if v_session.id is not null then
      update public.sms_qualification_sessions
      set status = 'opted_out', completed_at = now(), last_activity_at = now(), updated_at = now(),
          last_inbound_provider_id = v_source_provider_id,
          last_inbound_message_id = v_message.external_message_id
      where id = v_session.id;
    end if;
    if v_message.lead_id is not null then
      update public.leads
      set consent_to_contact = false,
          metadata = metadata || jsonb_build_object('sms_opted_out_at', now(), 'sms_opt_out_source', p_source_provider_key),
          updated_at = now()
      where id = v_message.lead_id;
    end if;
    return jsonb_build_object('should_send', false, 'reason', 'opted_out');
  end if;

  if v_session.id is null then
    insert into public.sms_qualification_sessions (
      property_id, lead_id, contact_phone_e164, sending_provider_id,
      sending_phone_e164, last_inbound_provider_id, last_inbound_message_id,
      metadata
    ) values (
      v_message.property_id, v_message.lead_id, v_contact, v_flow.sending_provider_id,
      v_flow.sending_phone_e164, v_source_provider_id, v_message.external_message_id,
      jsonb_build_object('entry_provider', p_source_provider_key, 'entry_message_id', v_message.external_message_id)
    ) returning * into v_session;

    v_next_prompt := nullif(v_flow.questions->0->>'prompt', '');
    v_reply := concat_ws(' ', nullif(v_flow.intro_message, ''), v_next_prompt);
  else
    if v_session.last_inbound_provider_id = v_source_provider_id
      and v_session.last_inbound_message_id = v_message.external_message_id then
      return jsonb_build_object('should_send', false, 'reason', 'duplicate_inbound', 'session_id', v_session.id);
    end if;

    v_answer_key := coalesce(nullif(v_flow.questions->v_session.current_step->>'key', ''), 'step_' || v_session.current_step);
    v_next_step := v_session.current_step + 1;
    v_next_prompt := nullif(v_flow.questions->v_next_step->>'prompt', '');
    v_reply := coalesce(v_next_prompt, v_flow.completion_message);

    update public.sms_qualification_sessions
    set answers = answers || jsonb_build_object(v_answer_key, coalesce(v_message.message_body, '')),
        current_step = v_next_step,
        status = case when v_next_prompt is null then 'completed' else 'active' end,
        completed_at = case when v_next_prompt is null then now() else null end,
        last_inbound_provider_id = v_source_provider_id,
        last_inbound_message_id = v_message.external_message_id,
        last_activity_at = now(),
        updated_at = now()
    where id = v_session.id
    returning * into v_session;
  end if;

  update public.sms_qualification_sessions
  set last_reply_text = v_reply, updated_at = now()
  where id = v_session.id;

  return jsonb_build_object(
    'should_send', v_reply is not null,
    'session_id', v_session.id,
    'property_id', v_message.property_id,
    'lead_id', coalesce(v_session.lead_id, v_message.lead_id),
    'to_phone', v_contact,
    'from_phone', v_flow.sending_phone_e164,
    'message', v_reply,
    'status', v_session.status,
    'step', v_session.current_step
  );
end;
$$;

create or replace function public.record_textmagic_outbound(
  p_external_message_id text,
  p_property_id bigint,
  p_lead_id bigint,
  p_from_phone text,
  p_to_phone text,
  p_message_body text,
  p_session_id bigint,
  p_provider_response jsonb,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_provider_id bigint;
  v_message_id bigint;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets where secret_key = 'fillout_ingest';
  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;

  select id into v_provider_id
  from public.integration_providers where provider_key = 'textmagic' and is_active;

  insert into public.sms_messages (
    provider_id, external_message_id, property_id, lead_id, direction,
    from_phone_e164, to_phone_e164, status, message_body, occurred_at, metadata
  ) values (
    v_provider_id, p_external_message_id, p_property_id, p_lead_id, 'outbound',
    private.normalize_e164(p_from_phone), private.normalize_e164(p_to_phone),
    'sent', p_message_body, now(),
    coalesce(p_provider_response, '{}'::jsonb) || jsonb_build_object('qualification_session_id', p_session_id)
  )
  on conflict (provider_id, external_message_id) do update
  set property_id = coalesce(excluded.property_id, public.sms_messages.property_id),
      lead_id = coalesce(excluded.lead_id, public.sms_messages.lead_id),
      status = excluded.status,
      message_body = excluded.message_body,
      metadata = public.sms_messages.metadata || excluded.metadata,
      updated_at = now()
  returning id into v_message_id;

  if p_lead_id is not null and not exists (
    select 1 from public.lead_interactions
    where provider_id = v_provider_id and source_event_id = p_external_message_id
  ) then
    insert into public.lead_interactions (
      lead_id, property_id, provider_id, source_event_id, conversation_id,
      interaction_type, channel, direction, status, content, occurred_at, metadata
    ) values (
      p_lead_id, p_property_id, v_provider_id, p_external_message_id,
      'sms-qualification:' || p_session_id, 'sms', 'sms', 'outbound', 'sent',
      p_message_body, now(), jsonb_build_object('sms_message_id', v_message_id, 'qualification_session_id', p_session_id)
    );
  end if;

  update public.sms_qualification_sessions
  set last_activity_at = now(), updated_at = now()
  where id = p_session_id;

  return jsonb_build_object('recorded', true, 'sms_message_id', v_message_id);
end;
$$;

create or replace view private.phone_routing_registry
with (security_invoker = true)
as
with callrail_numbers as (
  select
    cti.account_id,
    cti.account_name,
    cti.company_id,
    cti.company_name,
    cti.tracker_id,
    cti.tracker_name,
    cti.tracker_status,
    cti.destination_phone_e164,
    cti.sms_enabled,
    phone_e164
  from public.callrail_tracker_inventory cti
  cross join lateral unnest(cti.tracking_numbers) as phone_e164
)
select
  cn.phone_e164,
  cn.account_id as callrail_account_id,
  cn.account_name as callrail_account_name,
  cn.company_id as callrail_company_id,
  cn.company_name as callrail_company_name,
  cn.tracker_id as callrail_tracker_id,
  cn.tracker_name as callrail_tracker_name,
  cn.tracker_status as callrail_tracker_status,
  cn.destination_phone_e164 as current_forwarding_phone_e164,
  cn.sms_enabled as callrail_sms_enabled,
  vna.id as voice_number_assignment_id,
  vna.routing_status as bland_routing_status,
  vna.mapping_source,
  vna.confidence,
  p.id as property_id,
  p.property_key,
  p.domain,
  coalesce(pc.display_name, p.name) as display_name,
  vap.profile_key as bland_profile_key,
  vap.pathway_id as bland_pathway_id,
  coalesce(pvs.voice_id_override, vap.default_voice_id) as bland_voice_id,
  pvs.transfer_phone_e164,
  coalesce((pvs.settings->>'use_shared_voice')::boolean, true) as uses_shared_bland_agent,
  case
    when vna.id is null then 'unmapped'
    when vna.routing_status = 'conflict' then 'conflict'
    when vap.pathway_id is null then 'missing_agent_profile'
    else 'ready_for_bland_configuration'
  end as readiness
from callrail_numbers cn
left join public.voice_number_assignments vna
  on vna.phone_e164 = cn.phone_e164
left join public.properties p on p.id = vna.property_id
left join public.property_configurations pc on pc.property_id = p.id
left join public.property_voice_settings pvs on pvs.property_id = p.id
left join public.voice_agent_profiles vap on vap.id = pvs.voice_profile_id;

update public.property_voice_settings pvs
set transfer_phone_e164 = '+15085457447',
    settings = pvs.settings || jsonb_build_object(
      'callrail_forwarding_target', '+15085457447',
      'callrail_forwarding_mode', 'direct',
      'use_shared_voice', true
    ),
    updated_at = now()
from public.properties p
where p.id = pvs.property_id
  and p.domain = '3vsanantoniopaverservices.com';

revoke all on function public.start_sms_qualification(text, text, bigint, text) from public, anon, authenticated;
revoke all on function public.prepare_sms_qualification_reply(text, text, text) from public, anon, authenticated;
revoke all on function public.record_textmagic_outbound(text, bigint, bigint, text, text, text, bigint, jsonb, text) from public, anon, authenticated;
grant execute on function public.start_sms_qualification(text, text, bigint, text) to anon;
grant execute on function public.prepare_sms_qualification_reply(text, text, text) to anon;
grant execute on function public.record_textmagic_outbound(text, bigint, bigint, text, text, text, bigint, jsonb, text) to anon;

comment on table public.sms_qualification_flows is
'Provider-neutral, per-property SMS qualification scripts. The initial pilot sends through TextMagic.';
comment on table public.sms_qualification_sessions is
'State and answers for one lead qualification conversation across CallRail ingress and TextMagic replies.';
comment on view private.phone_routing_registry is
'Master inventory of every active CallRail-owned number with its property and reusable Bland pathway mapping when known.';
