insert into public.integration_providers (provider_key, name, category, credential_location, is_active)
values ('textmagic', 'TextMagic', 'communications', 'external_secret_store', true)
on conflict (provider_key) do update
set name = excluded.name,
    category = excluded.category,
    credential_location = excluded.credential_location,
    is_active = true;

create table if not exists public.sms_number_assignments (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.integration_providers(id),
  property_id bigint not null references public.properties(id),
  phone_e164 text not null,
  external_number_id text,
  label text,
  routing_status text not null default 'inventory'
    check (routing_status in ('inventory', 'testing', 'active', 'paused', 'retired')),
  is_primary boolean not null default false,
  capabilities jsonb not null default '{"sms":true,"mms":false}'::jsonb
    check (jsonb_typeof(capabilities) = 'object'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_id, phone_e164),
  check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$')
);

create index if not exists sms_number_assignments_property_status_idx
  on public.sms_number_assignments (property_id, routing_status);

create unique index if not exists sms_number_assignments_one_primary_idx
  on public.sms_number_assignments (property_id)
  where is_primary and routing_status in ('testing', 'active');

create table if not exists public.sms_messages (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.integration_providers(id),
  external_message_id text not null,
  property_id bigint references public.properties(id),
  lead_id bigint references public.leads(id),
  number_assignment_id bigint references public.sms_number_assignments(id),
  direction text not null check (direction in ('inbound', 'outbound')),
  from_phone_e164 text,
  to_phone_e164 text,
  status text not null default 'received',
  message_body text,
  occurred_at timestamptz not null default now(),
  delivered_at timestamptz,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_id, external_message_id)
);

create index if not exists sms_messages_property_occurred_idx
  on public.sms_messages (property_id, occurred_at desc);
create index if not exists sms_messages_lead_occurred_idx
  on public.sms_messages (lead_id, occurred_at desc)
  where lead_id is not null;
create index if not exists sms_messages_contact_lookup_idx
  on public.sms_messages (property_id, from_phone_e164, occurred_at desc)
  where direction = 'inbound';

alter table public.sms_number_assignments enable row level security;
alter table public.sms_messages enable row level security;
revoke all on public.sms_number_assignments from anon, authenticated;
revoke all on public.sms_messages from anon, authenticated;

insert into public.sms_number_assignments (
  provider_id, property_id, phone_e164, label, routing_status, is_primary, capabilities, metadata
)
select ip.id, p.id, '+18337689020', '3V lead texts', 'testing', true,
       '{"sms":true,"mms":true,"voice":true,"toll_free_registered":true}'::jsonb,
       jsonb_build_object(
         'pilot', 'verified-five-v1',
         'account_label', 'Lead texts',
         'next_renewal', '2026-08-14',
         'call_forwarding_target', '+16195696541'
       )
from public.integration_providers ip
join public.properties p on p.domain = '3vsanantoniopaverservices.com'
where ip.provider_key = 'textmagic'
on conflict (provider_id, phone_e164) do update
set property_id = excluded.property_id,
    label = excluded.label,
    routing_status = excluded.routing_status,
    is_primary = excluded.is_primary,
    capabilities = excluded.capabilities,
    metadata = public.sms_number_assignments.metadata || excluded.metadata,
    updated_at = now();

create or replace function public.ingest_textmagic_event(
  p_event_type text,
  p_payload jsonb,
  p_request_id text,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_provider_id bigint;
  v_external_id text;
  v_event_id bigint;
  v_message_id bigint;
  v_assignment_id bigint;
  v_property_id bigint;
  v_market_id bigint;
  v_lead_id bigint;
  v_service_id bigint;
  v_direction text;
  v_from text;
  v_to text;
  v_body text;
  v_status text;
  v_occurred_at timestamptz;
  v_test_mode boolean := true;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'fillout_ingest';

  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;
  if p_event_type not in ('inbound', 'delivery') or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'invalid textmagic event' using errcode = '22023';
  end if;

  select id into v_provider_id
  from public.integration_providers
  where provider_key = 'textmagic' and is_active;

  v_external_id := coalesce(
    nullif(p_payload->>'messageId', ''), nullif(p_payload->>'message_id', ''),
    nullif(p_payload->>'messageid', ''), nullif(p_payload->>'id', ''), p_request_id
  );
  v_direction := case when p_event_type = 'inbound' then 'inbound' else 'outbound' end;
  v_from := private.normalize_e164(coalesce(
    p_payload->>'sender', p_payload->>'from', p_payload->>'source',
    case when p_event_type = 'inbound' then p_payload->>'phone' end
  ));
  v_to := private.normalize_e164(coalesce(
    p_payload->>'receiver', p_payload->>'to', p_payload->>'destination',
    case when p_event_type = 'delivery' then p_payload->>'phone' end
  ));
  v_body := nullif(coalesce(p_payload->>'text', p_payload->>'message', p_payload->>'body'), '');
  v_status := lower(coalesce(nullif(p_payload->>'status', ''),
    case when p_event_type = 'inbound' then 'received' else 'updated' end));
  begin
    v_occurred_at := coalesce(
      nullif(p_payload->>'messageTime', '')::timestamptz,
      nullif(p_payload->>'message_time', '')::timestamptz,
      nullif(p_payload->>'timestamp', '')::timestamptz,
      now()
    );
  exception when others then
    v_occurred_at := now();
  end;

  if p_event_type = 'inbound' then
    select sna.id, sna.property_id, p.market_id, coalesce(pc.test_mode, true)
    into v_assignment_id, v_property_id, v_market_id, v_test_mode
    from public.sms_number_assignments sna
    join public.properties p on p.id = sna.property_id
    left join public.property_configurations pc on pc.property_id = p.id
    where sna.phone_e164 = v_to
      and sna.routing_status in ('testing', 'active')
    order by sna.is_primary desc, sna.id
    limit 1;
  else
    select sm.number_assignment_id, sm.property_id, p.market_id, coalesce(pc.test_mode, true), sm.lead_id
    into v_assignment_id, v_property_id, v_market_id, v_test_mode, v_lead_id
    from public.sms_messages sm
    left join public.properties p on p.id = sm.property_id
    left join public.property_configurations pc on pc.property_id = p.id
    where sm.provider_id = v_provider_id and sm.external_message_id = v_external_id;
  end if;

  insert into public.webhook_events (
    source_system, event_id, event_type, status, payload, received_at, attempt_count
  ) values (
    'textmagic', p_event_type || ':' || v_external_id, p_event_type, 'processing', p_payload, now(), 1
  )
  on conflict (source_system, event_id) do update
  set payload = excluded.payload,
      status = 'processing',
      attempt_count = public.webhook_events.attempt_count + 1,
      error_message = null
  returning id into v_event_id;

  if p_event_type = 'inbound' and v_property_id is not null and v_from is not null then
    select l.id into v_lead_id
    from public.leads l
    where l.property_id = v_property_id
      and l.normalized_phone = v_from
      and l.created_at >= now() - interval '90 days'
    order by l.created_at desc
    limit 1;

    if v_lead_id is null then
      select ps.service_id into v_service_id
      from public.property_services ps
      where ps.property_id = v_property_id and ps.is_active and ps.accepting_leads
      order by ps.is_primary desc, ps.sort_order, ps.service_id
      limit 1;

      insert into public.leads (
        ingestion_key, source_system, source_record_id, source_event_id,
        property_id, market_id, service_id, received_at, occurred_at,
        phone, normalized_phone, lead_source, source_category,
        communication_channel, conversion_source, status, qualification_status,
        is_billable, consent_to_contact, metadata
      ) values (
        'textmagic:' || v_property_id || ':' || v_from, 'textmagic', v_external_id, v_event_id,
        v_property_id, v_market_id, v_service_id, now(), v_occurred_at,
        v_from, v_from, 'TextMagic SMS', 'direct', 'text', 'TextMagic',
        case when v_test_mode then 'validating' else 'new' end,
        case when v_test_mode then 'needs_review' else 'unreviewed' end,
        case when v_test_mode then false else null end, true,
        jsonb_build_object('test_mode', v_test_mode, 'first_message', v_body, 'request_id', p_request_id)
      ) returning id into v_lead_id;
    end if;
  end if;

  insert into public.sms_messages (
    provider_id, external_message_id, property_id, lead_id, number_assignment_id,
    direction, from_phone_e164, to_phone_e164, status, message_body, occurred_at,
    delivered_at, metadata
  ) values (
    v_provider_id, v_external_id, v_property_id, v_lead_id, v_assignment_id,
    v_direction, v_from, v_to, v_status, v_body, v_occurred_at,
    case when v_status in ('delivered', 'd') then v_occurred_at else null end,
    p_payload || jsonb_build_object('request_id', p_request_id, 'event_type', p_event_type, 'test_mode', v_test_mode)
  )
  on conflict (provider_id, external_message_id) do update
  set property_id = coalesce(excluded.property_id, public.sms_messages.property_id),
      lead_id = coalesce(excluded.lead_id, public.sms_messages.lead_id),
      number_assignment_id = coalesce(excluded.number_assignment_id, public.sms_messages.number_assignment_id),
      status = excluded.status,
      message_body = coalesce(excluded.message_body, public.sms_messages.message_body),
      delivered_at = coalesce(excluded.delivered_at, public.sms_messages.delivered_at),
      metadata = public.sms_messages.metadata || excluded.metadata,
      updated_at = now()
  returning id into v_message_id;

  if p_event_type = 'inbound' and v_lead_id is not null and not exists (
    select 1 from public.lead_interactions li
    where li.provider_id = v_provider_id and li.source_event_id = v_external_id
  ) then
    insert into public.lead_interactions (
      lead_id, property_id, provider_id, source_event_id, conversation_id,
      interaction_type, channel, direction, status, content, occurred_at, metadata
    ) values (
      v_lead_id, v_property_id, v_provider_id, v_external_id,
      'textmagic:' || v_property_id || ':' || v_from,
      'sms', 'sms', 'inbound', v_status, v_body, v_occurred_at,
      jsonb_build_object('sms_message_id', v_message_id, 'number_assignment_id', v_assignment_id, 'test_mode', v_test_mode)
    );
  end if;

  update public.webhook_events
  set status = 'processed', processed_at = now()
  where id = v_event_id;

  return jsonb_build_object(
    'accepted', true,
    'event_type', p_event_type,
    'external_message_id', v_external_id,
    'sms_message_id', v_message_id,
    'property_id', v_property_id,
    'lead_id', v_lead_id,
    'matched', v_property_id is not null,
    'test_mode', v_test_mode
  );
exception when others then
  if v_event_id is not null then
    update public.webhook_events
    set status = 'failed', error_message = sqlerrm
    where id = v_event_id;
  end if;
  raise;
end;
$$;

revoke all on function public.ingest_textmagic_event(text, jsonb, text, text) from public, anon, authenticated;
grant execute on function public.ingest_textmagic_event(text, jsonb, text, text) to anon;

create or replace function public.get_pilot_site_config(
  p_site_key text,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_config jsonb;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'fillout_ingest';
  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized configuration request' using errcode = '28000';
  end if;

  select jsonb_build_object(
    'property_key', p.property_key,
    'domain', p.domain,
    'display_name', coalesce(pc.display_name, p.name),
    'primary_phone', coalesce(p.primary_phone, ''),
    'sms_phone', coalesce((
      select sna.phone_e164
      from public.sms_number_assignments sna
      where sna.property_id = p.id
        and sna.routing_status in ('testing', 'active')
        and coalesce((sna.capabilities->>'sms')::boolean, false)
      order by sna.is_primary desc, sna.id
      limit 1
    ), ''),
    'sms_enabled', exists (
      select 1 from public.sms_number_assignments sna
      where sna.property_id = p.id
        and sna.routing_status in ('testing', 'active')
        and coalesce((sna.capabilities->>'sms')::boolean, false)
    ),
    'city', coalesce(p.city, ''),
    'state_region', coalesce(p.state_region, ''),
    'timezone', coalesce(pc.timezone, ''),
    'consent_disclosure', coalesce(pc.consent_disclosure, ''),
    'test_mode', pc.test_mode,
    'form', (
      select jsonb_build_object('provider', 'fillout', 'form_id', ft.fillout_form_id,
        'template_key', ft.template_key, 'status', ft.status)
      from public.property_form_templates pft
      join public.form_templates ft on ft.id = pft.form_template_id
      where pft.property_id = p.id and pft.is_active and pft.is_primary
        and ft.webhook_enabled and ft.status in ('testing', 'active') and ft.fillout_form_id is not null
      order by ft.id limit 1
    ),
    'services', coalesce((
      select jsonb_agg(jsonb_build_object('slug', s.slug, 'name', coalesce(ps.public_name, s.name))
        order by ps.sort_order, s.name)
      from public.property_services ps
      join public.services s on s.id = ps.service_id
      where ps.property_id = p.id and ps.is_active and ps.accepting_leads and s.is_active
    ), '[]'::jsonb)
  ) into v_config
  from public.properties p
  join public.property_configurations pc on pc.property_id = p.id
  join public.property_voice_settings pvs on pvs.property_id = p.id
  where p.property_key = lower(btrim(p_site_key))
    and p.status in ('onboarding', 'active')
    and pc.test_mode
    and coalesce((pc.brand_settings->>'lead_pilot_enabled')::boolean, false)
    and pvs.status = 'testing' and pvs.test_mode
    and coalesce((pvs.settings->>'pilot_scope')::boolean, false)
    and pvs.settings->>'pilot_cohort' = 'verified-five-v1'
    and exists (
      select 1 from public.property_form_templates pft
      join public.form_templates ft on ft.id = pft.form_template_id
      where pft.property_id = p.id and pft.is_active and pft.is_primary
        and ft.webhook_enabled and ft.status in ('testing', 'active') and ft.fillout_form_id is not null
    );
  return v_config;
end;
$$;

revoke all on function public.get_pilot_site_config(text, text) from public, anon, authenticated;
grant execute on function public.get_pilot_site_config(text, text) to anon;

comment on table public.sms_number_assignments is
'Deterministic SMS number-to-property routing. A shared number must not be active for more than one property.';
comment on table public.sms_messages is
'Normalized TextMagic message ledger linked to the property and lead whenever the receiving number is mapped.';
