create table if not exists public.voice_agent_profiles (
  id bigint generated by default as identity primary key,
  profile_key text not null unique,
  provider_id bigint not null references public.integration_providers(id) on delete restrict,
  name text not null,
  direction_scope text not null default 'both'
    check (direction_scope in ('inbound', 'outbound', 'both')),
  pathway_id text,
  pathway_version integer check (pathway_version is null or pathway_version > 0),
  default_voice_id text,
  status text not null default 'draft'
    check (status in ('draft', 'testing', 'active', 'paused', 'retired')),
  settings jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists voice_agent_profiles_provider_id_idx
  on public.voice_agent_profiles(provider_id);

create table if not exists public.property_voice_settings (
  property_id bigint primary key references public.properties(id) on delete cascade,
  voice_profile_id bigint not null references public.voice_agent_profiles(id) on delete restrict,
  status text not null default 'draft'
    check (status in ('draft', 'testing', 'active', 'paused', 'blocked')),
  voice_id_override text,
  transfer_phone_e164 text
    check (transfer_phone_e164 is null or transfer_phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  test_mode boolean not null default true,
  settings jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists property_voice_settings_voice_profile_id_idx
  on public.property_voice_settings(voice_profile_id);

create table if not exists public.voice_number_assignments (
  id bigint generated by default as identity primary key,
  phone_e164 text not null check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  property_id bigint not null references public.properties(id) on delete cascade,
  provider_id bigint references public.integration_providers(id) on delete restrict,
  external_number_id text,
  number_role text not null default 'website'
    check (number_role in ('website', 'tracking', 'inbound', 'outbound', 'transfer')),
  routing_status text not null default 'inventory'
    check (routing_status in ('inventory', 'conflict', 'testing', 'active', 'paused', 'retired')),
  is_primary boolean not null default false,
  mapping_source text not null default 'manual',
  confidence numeric(4,3) not null default 1.000 check (confidence between 0 and 1),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (phone_e164, property_id, number_role)
);

create index if not exists voice_number_assignments_property_id_idx
  on public.voice_number_assignments(property_id);
create index if not exists voice_number_assignments_provider_id_idx
  on public.voice_number_assignments(provider_id) where provider_id is not null;
create index if not exists voice_number_assignments_route_lookup_idx
  on public.voice_number_assignments(phone_e164, routing_status);
create unique index if not exists voice_number_assignments_one_active_route_idx
  on public.voice_number_assignments(phone_e164)
  where routing_status in ('testing', 'active')
    and number_role in ('website', 'tracking', 'inbound');

create table if not exists public.voice_calls (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  provider_id bigint not null references public.integration_providers(id) on delete restrict,
  external_call_id text not null,
  property_id bigint references public.properties(id) on delete restrict,
  lead_id bigint references public.leads(id) on delete set null,
  number_assignment_id bigint references public.voice_number_assignments(id) on delete set null,
  direction text not null check (direction in ('inbound', 'outbound')),
  caller_phone_e164 text check (caller_phone_e164 is null or caller_phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  dialed_phone_e164 text check (dialed_phone_e164 is null or dialed_phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  mapping_status text not null default 'unmatched'
    check (mapping_status in ('matched', 'unmatched', 'ambiguous')),
  status text not null default 'received',
  answered_by text,
  pathway_id text,
  pathway_version integer,
  voice_id text,
  started_at timestamptz,
  ended_at timestamptz,
  duration_seconds numeric(10,2) check (duration_seconds is null or duration_seconds >= 0),
  summary text,
  transcript text,
  recording_url text,
  analysis jsonb not null default '{}'::jsonb check (jsonb_typeof(analysis) = 'object'),
  variables jsonb not null default '{}'::jsonb check (jsonb_typeof(variables) = 'object'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  test_mode boolean not null default true,
  received_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_id, external_call_id)
);

create index if not exists voice_calls_property_started_idx
  on public.voice_calls(property_id, started_at desc) where property_id is not null;
create index if not exists voice_calls_lead_id_idx
  on public.voice_calls(lead_id) where lead_id is not null;
create index if not exists voice_calls_mapping_status_received_idx
  on public.voice_calls(mapping_status, received_at desc);
create index if not exists voice_calls_number_assignment_id_idx
  on public.voice_calls(number_assignment_id) where number_assignment_id is not null;

create table if not exists private.bland_webhook_inbox (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  external_call_id text,
  event_type text not null default 'post_call',
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  status text not null default 'received'
    check (status in ('received', 'processed', 'rejected')),
  error_message text,
  received_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bland_webhook_inbox_call_id_idx
  on private.bland_webhook_inbox(external_call_id) where external_call_id is not null;
create index if not exists bland_webhook_inbox_received_at_idx
  on private.bland_webhook_inbox(received_at desc);

alter table public.voice_agent_profiles enable row level security;
alter table public.property_voice_settings enable row level security;
alter table public.voice_number_assignments enable row level security;
alter table public.voice_calls enable row level security;

revoke all on public.voice_agent_profiles from anon, authenticated;
revoke all on public.property_voice_settings from anon, authenticated;
revoke all on public.voice_number_assignments from anon, authenticated;
revoke all on public.voice_calls from anon, authenticated;
revoke all on private.bland_webhook_inbox from public, anon, authenticated;

create or replace function private.normalize_e164(p_value text)
returns text
language sql
immutable
strict
set search_path = pg_temp
as $$
  with normalized as (
    select btrim(p_value) as raw_value,
           regexp_replace(p_value, '[^0-9]', '', 'g') as digits
  )
  select case
    when raw_value ~ '^\+[1-9][0-9]{7,14}$' then raw_value
    when length(digits) = 10 then '+1' || digits
    when length(digits) between 8 and 15 and digits ~ '^[1-9]' then '+' || digits
    else null
  end
  from normalized;
$$;

revoke all on function private.normalize_e164(text) from public, anon, authenticated;

insert into public.voice_agent_profiles (
  profile_key, provider_id, name, direction_scope, status, settings
)
select
  'llg-universal-qualification', ip.id, 'LLG Universal Lead Qualification', 'both', 'testing',
  jsonb_build_object(
    'strategy', 'shared_pathway_property_context',
    'voice_strategy', 'single_default_with_property_override',
    'ai_disclosure_required', true,
    'outbound_requires_consent', true,
    'production_calls_enabled', false,
    'analysis_schema_version', 1
  )
from public.integration_providers ip
where ip.provider_key = 'bland_ai'
on conflict (profile_key) do update
set provider_id = excluded.provider_id,
    name = excluded.name,
    direction_scope = excluded.direction_scope,
    settings = public.voice_agent_profiles.settings || excluded.settings,
    updated_at = now();

insert into public.property_voice_settings (
  property_id, voice_profile_id, status, test_mode, settings
)
select p.id, vap.id, 'testing', coalesce(pc.test_mode, true),
  jsonb_build_object(
    'configuration_source', 'property_configuration',
    'use_shared_voice', true,
    'allow_transfer', false
  )
from public.properties p
cross join public.voice_agent_profiles vap
left join public.property_configurations pc on pc.property_id = p.id
where vap.profile_key = 'llg-universal-qualification'
on conflict (property_id) do update
set voice_profile_id = excluded.voice_profile_id,
    test_mode = excluded.test_mode,
    settings = public.property_voice_settings.settings || excluded.settings,
    updated_at = now();

with normalized as (
  select p.id as property_id, private.normalize_e164(p.primary_phone) as phone_e164
  from public.properties p
  where nullif(btrim(p.primary_phone), '') is not null
), classified as (
  select n.property_id, n.phone_e164,
         count(*) over (partition by n.phone_e164) as assignment_count
  from normalized n
  where n.phone_e164 is not null
)
insert into public.voice_number_assignments (
  phone_e164, property_id, number_role, routing_status, is_primary,
  mapping_source, confidence, metadata
)
select phone_e164, property_id, 'website',
       case when assignment_count > 1 then 'conflict' else 'inventory' end,
       true, 'properties.primary_phone',
       case when assignment_count > 1 then 0.500 else 0.950 end,
       jsonb_build_object(
         'requires_provider_verification', true,
         'duplicate_property_count', assignment_count,
         'bland_inventory_status', 'not_present'
       )
from classified
on conflict (phone_e164, property_id, number_role) do update
set routing_status = excluded.routing_status,
    is_primary = true,
    mapping_source = excluded.mapping_source,
    confidence = excluded.confidence,
    metadata = public.voice_number_assignments.metadata || excluded.metadata,
    updated_at = now();

create or replace function public.record_bland_webhook_attempt(
  p_payload jsonb,
  p_request_id text,
  p_ingest_token text,
  p_status text default 'received',
  p_error_message text default null,
  p_event_type text default 'post_call'
)
returns bigint
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_inbox_id bigint;
  v_call_id text;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'bland_ingest';

  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;

  if jsonb_typeof(p_payload) <> 'object' then
    raise exception 'invalid webhook payload' using errcode = '22023';
  end if;
  if p_status not in ('received', 'processed', 'rejected') then
    raise exception 'invalid webhook status' using errcode = '22023';
  end if;

  v_call_id := coalesce(nullif(p_payload->>'call_id', ''), nullif(p_payload->>'c_id', ''));

  insert into private.bland_webhook_inbox (
    request_id, external_call_id, event_type, payload, status, error_message
  ) values (
    p_request_id, v_call_id, coalesce(nullif(p_event_type, ''), 'post_call'),
    p_payload, p_status, nullif(p_error_message, '')
  )
  on conflict (request_id) do update
  set external_call_id = excluded.external_call_id,
      payload = excluded.payload,
      status = excluded.status,
      error_message = excluded.error_message,
      updated_at = now()
  returning id into v_inbox_id;

  return v_inbox_id;
end;
$$;

create or replace function public.get_bland_voice_context(
  p_phone_number text,
  p_property_key text,
  p_lead_public_id uuid,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_phone text;
  v_property_id bigint;
  v_assignment_id bigint;
  v_context jsonb;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'bland_ingest';

  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized context request' using errcode = '28000';
  end if;

  v_phone := private.normalize_e164(p_phone_number);

  if nullif(btrim(p_property_key), '') is not null then
    select p.id into v_property_id
    from public.properties p
    where p.property_key = btrim(p_property_key);
  end if;

  if v_property_id is null and v_phone is not null then
    select vna.property_id, vna.id
    into v_property_id, v_assignment_id
    from public.voice_number_assignments vna
    where vna.phone_e164 = v_phone
      and vna.routing_status in ('inventory', 'testing', 'active')
      and vna.number_role in ('website', 'tracking', 'inbound')
    order by case vna.routing_status when 'active' then 1 when 'testing' then 2 else 3 end,
             vna.is_primary desc,
             vna.id
    limit 1;
  end if;

  if v_property_id is null then
    return jsonb_build_object(
      'matched', false,
      'phone_number', v_phone,
      'reason', 'unmapped_or_conflicted_number'
    );
  end if;

  select jsonb_build_object(
    'matched', true,
    'property_id', p.id,
    'property_key', p.property_key,
    'number_assignment_id', v_assignment_id,
    'company', jsonb_build_object(
      'display_name', coalesce(nullif(pc.display_name, ''), p.name),
      'legal_business_name', pc.legal_business_name,
      'domain', p.domain,
      'website_url', p.website_url,
      'primary_phone', p.primary_phone,
      'primary_email', p.primary_email,
      'city', p.city,
      'state_region', p.state_region,
      'timezone', coalesce(pc.timezone, 'America/New_York'),
      'locale', coalesce(pc.locale, 'en-US')
    ),
    'assistant', jsonb_build_object(
      'name', coalesce(nullif(pc.assistant_name, ''), 'Alex'),
      'ai_disclosure', coalesce(nullif(pc.consent_disclosure, ''), 'I am an AI assistant helping this local service company respond to inquiries.'),
      'after_hours_behavior', coalesce(pc.after_hours_behavior, 'capture_only'),
      'test_mode', coalesce(pvs.test_mode, pc.test_mode, true),
      'profile_key', vap.profile_key,
      'pathway_id', vap.pathway_id,
      'pathway_version', vap.pathway_version,
      'voice_id', coalesce(pvs.voice_id_override, vap.default_voice_id),
      'transfer_phone', pvs.transfer_phone_e164,
      'settings', coalesce(vap.settings, '{}'::jsonb) || coalesce(pvs.settings, '{}'::jsonb)
    ),
    'services', coalesce((
      select jsonb_agg(jsonb_build_object(
        'service_id', s.id,
        'slug', s.slug,
        'name', coalesce(nullif(ps.public_name, ''), s.name),
        'description', ps.description,
        'is_primary', ps.is_primary,
        'accepting_leads', ps.accepting_leads,
        'qualification_mode', ps.qualification_mode
      ) order by ps.is_primary desc, ps.sort_order, s.name)
      from public.property_services ps
      join public.services s on s.id = ps.service_id
      where ps.property_id = p.id and ps.is_active
    ), '[]'::jsonb),
    'service_areas', coalesce((
      select jsonb_agg(jsonb_build_object(
        'area_type', sa.area_type,
        'state_region', sa.state_region,
        'county', sa.county,
        'city', sa.city,
        'postal_code', sa.postal_code,
        'radius_miles', sa.radius_miles,
        'included', sa.is_included
      ) order by sa.priority, sa.id)
      from public.service_areas sa
      where sa.property_id = p.id and sa.is_active
    ), '[]'::jsonb),
    'availability', coalesce((
      select jsonb_agg(jsonb_build_object(
        'day_of_week', paw.day_of_week,
        'start_local', paw.start_local,
        'end_local', paw.end_local,
        'timezone', paw.timezone,
        'capacity', paw.capacity
      ) order by paw.day_of_week, paw.start_local)
      from public.property_availability_windows paw
      where paw.property_id = p.id
        and paw.is_active
        and paw.effective_from <= current_date
        and (paw.effective_until is null or paw.effective_until >= current_date)
    ), '[]'::jsonb),
    'lead', case when l.id is null then null else jsonb_build_object(
      'lead_id', l.id,
      'lead_public_id', l.public_id,
      'first_name', l.first_name,
      'full_name', l.full_name,
      'phone', l.phone,
      'email', l.email,
      'service_id', l.service_id,
      'status', l.status,
      'consent_to_contact', l.consent_to_contact,
      'metadata', l.metadata
    ) end
  ) into v_context
  from public.properties p
  left join public.property_configurations pc on pc.property_id = p.id
  left join public.property_voice_settings pvs on pvs.property_id = p.id
  left join public.voice_agent_profiles vap on vap.id = pvs.voice_profile_id
  left join public.leads l on l.public_id = p_lead_public_id and l.property_id = p.id
  where p.id = v_property_id;

  return v_context;
end;
$$;

create or replace function public.ingest_bland_call(
  p_payload jsonb,
  p_request_id text,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_provider_id bigint;
  v_call_id text;
  v_inbound boolean;
  v_direction text;
  v_caller_phone text;
  v_dialed_phone text;
  v_property_key text;
  v_property_id bigint;
  v_assignment_id bigint;
  v_lead_id bigint;
  v_service_id bigint;
  v_market_id bigint;
  v_test_mode boolean := true;
  v_mapping_status text := 'unmatched';
  v_event_id bigint;
  v_voice_call_id bigint;
  v_variables jsonb;
  v_analysis jsonb;
  v_metadata jsonb;
  v_status text;
  v_started_at timestamptz;
  v_duration_seconds numeric;
  v_name text;
  v_callback_phone text;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'bland_ingest';

  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;
  if jsonb_typeof(p_payload) <> 'object' then
    raise exception 'invalid call payload' using errcode = '22023';
  end if;

  v_call_id := coalesce(nullif(p_payload->>'call_id', ''), nullif(p_payload->>'c_id', ''));
  if v_call_id is null then
    raise exception 'missing call id' using errcode = '22023';
  end if;

  select id into v_provider_id
  from public.integration_providers
  where provider_key = 'bland_ai' and is_active;
  if v_provider_id is null then
    raise exception 'Bland provider not configured' using errcode = 'P0002';
  end if;

  v_variables := case when jsonb_typeof(p_payload->'variables') = 'object' then p_payload->'variables' else '{}'::jsonb end;
  v_analysis := case when jsonb_typeof(p_payload->'analysis') = 'object' then p_payload->'analysis' else '{}'::jsonb end;
  v_metadata := case when jsonb_typeof(p_payload->'metadata') = 'object' then p_payload->'metadata' else '{}'::jsonb end;
  v_inbound := coalesce(nullif(p_payload->>'inbound', '')::boolean, false);
  v_direction := case when v_inbound then 'inbound' else 'outbound' end;
  v_caller_phone := private.normalize_e164(case when v_inbound then p_payload->>'from' else p_payload->>'to' end);
  v_dialed_phone := private.normalize_e164(case when v_inbound then p_payload->>'to' else p_payload->>'from' end);
  v_property_key := coalesce(
    nullif(v_metadata->>'property_key', ''),
    nullif(v_variables->>'property_key', ''),
    nullif(p_payload->'request_data'->>'property_key', '')
  );

  if v_property_key is not null then
    select p.id, p.market_id, coalesce(pc.test_mode, true)
    into v_property_id, v_market_id, v_test_mode
    from public.properties p
    left join public.property_configurations pc on pc.property_id = p.id
    where p.property_key = v_property_key;
  elsif v_dialed_phone is not null then
    select vna.property_id, vna.id, p.market_id, coalesce(pvs.test_mode, pc.test_mode, true)
    into v_property_id, v_assignment_id, v_market_id, v_test_mode
    from public.voice_number_assignments vna
    join public.properties p on p.id = vna.property_id
    left join public.property_configurations pc on pc.property_id = p.id
    left join public.property_voice_settings pvs on pvs.property_id = p.id
    where vna.phone_e164 = v_dialed_phone
      and vna.routing_status in ('inventory', 'testing', 'active')
      and vna.number_role in ('website', 'tracking', 'inbound', 'outbound')
    order by case vna.routing_status when 'active' then 1 when 'testing' then 2 else 3 end,
             vna.is_primary desc,
             vna.id
    limit 1;
  end if;

  if v_property_id is not null then
    v_mapping_status := 'matched';
  end if;

  if nullif(v_metadata->>'lead_public_id', '') is not null then
    select l.id into v_lead_id
    from public.leads l
    where l.public_id = (v_metadata->>'lead_public_id')::uuid
      and (v_property_id is null or l.property_id = v_property_id);
  elsif nullif(v_metadata->>'lead_id', '') ~ '^[0-9]+$' then
    select l.id into v_lead_id
    from public.leads l
    where l.id = (v_metadata->>'lead_id')::bigint
      and (v_property_id is null or l.property_id = v_property_id);
  end if;

  insert into public.webhook_events (
    source_system, event_id, event_type, status, payload, received_at, attempt_count
  ) values (
    'bland_ai', v_call_id, 'post_call', 'processing', p_payload, now(), 1
  )
  on conflict (source_system, event_id) do update
  set payload = excluded.payload,
      status = 'processing',
      attempt_count = public.webhook_events.attempt_count + 1,
      error_message = null
  returning id into v_event_id;

  if v_lead_id is null and v_inbound and v_property_id is not null then
    v_callback_phone := coalesce(
      private.normalize_e164(v_variables->>'callback_number'),
      private.normalize_e164(v_analysis->>'callback_number'),
      v_caller_phone
    );
    v_name := coalesce(
      nullif(v_variables->>'caller_name', ''),
      nullif(v_analysis->>'caller_name', ''),
      nullif(v_analysis->>'name', '')
    );

    if v_callback_phone is not null then
      select ps.service_id into v_service_id
      from public.property_services ps
      where ps.property_id = v_property_id and ps.is_active and ps.accepting_leads
      order by ps.is_primary desc, ps.sort_order, ps.service_id
      limit 1;

      insert into public.leads (
        ingestion_key, source_system, source_record_id, source_event_id,
        property_id, market_id, service_id, received_at, occurred_at,
        full_name, phone, normalized_phone, email, normalized_email,
        address_line_1, city, state_region, postal_code,
        lead_source, source_category, communication_channel, conversion_source,
        bland_call_id, status, qualification_status, is_billable,
        consent_to_contact, metadata
      ) values (
        'bland_ai:' || v_call_id, 'bland_ai', v_call_id, v_event_id,
        v_property_id, v_market_id, v_service_id, now(),
        coalesce(nullif(p_payload->>'started_at', '')::timestamptz, nullif(p_payload->>'created_at', '')::timestamptz, now()),
        v_name, v_callback_phone, v_callback_phone,
        nullif(lower(coalesce(v_variables->>'email', v_analysis->>'email')), ''),
        nullif(lower(coalesce(v_variables->>'email', v_analysis->>'email')), ''),
        nullif(coalesce(v_variables->>'caller_address', v_analysis->>'address'), ''),
        nullif(v_analysis->>'city', ''), nullif(v_analysis->>'state_region', ''), nullif(v_analysis->>'postal_code', ''),
        'Bland.ai Voice', 'direct', 'call', 'Bland.ai', v_call_id,
        case when v_test_mode then 'validating' else 'new' end,
        case when v_test_mode then 'needs_review' else 'unreviewed' end,
        case when v_test_mode then false else null end,
        false,
        jsonb_build_object(
          'request_id', p_request_id,
          'test_mode', v_test_mode,
          'voice_variables', v_variables,
          'voice_analysis', v_analysis,
          'service_interest', coalesce(v_variables->>'service_interest', v_analysis->>'service_requested'),
          'consent_pending', true
        )
      )
      on conflict (source_system, source_record_id) do update
      set updated_at = now(),
          metadata = public.leads.metadata || excluded.metadata
      returning id into v_lead_id;
    end if;
  end if;

  v_status := coalesce(
    nullif(p_payload->>'status', ''),
    nullif(p_payload->>'queue_status', ''),
    case when coalesce(nullif(p_payload->>'completed', '')::boolean, false) then 'completed' else 'received' end
  );
  v_started_at := coalesce(
    nullif(p_payload->>'started_at', '')::timestamptz,
    nullif(p_payload->>'created_at', '')::timestamptz,
    now()
  );
  v_duration_seconds := case
    when nullif(p_payload->>'call_length', '') is not null then (p_payload->>'call_length')::numeric * 60
    else null
  end;

  insert into public.voice_calls (
    provider_id, external_call_id, property_id, lead_id, number_assignment_id,
    direction, caller_phone_e164, dialed_phone_e164, mapping_status, status,
    answered_by, pathway_id, pathway_version, voice_id, started_at,
    duration_seconds, summary, transcript, recording_url, analysis, variables,
    metadata, test_mode
  ) values (
    v_provider_id, v_call_id, v_property_id, v_lead_id, v_assignment_id,
    v_direction, v_caller_phone, v_dialed_phone, v_mapping_status, v_status,
    nullif(p_payload->>'answered_by', ''), nullif(p_payload->>'pathway_id', ''),
    nullif(p_payload->>'pathway_version', '')::integer, nullif(p_payload->>'voice_id', ''),
    v_started_at, v_duration_seconds, nullif(p_payload->>'summary', ''),
    nullif(p_payload->>'concatenated_transcript', ''), nullif(p_payload->>'recording_url', ''),
    v_analysis, v_variables,
    v_metadata || jsonb_build_object('request_id', p_request_id, 'raw_to', p_payload->>'to', 'raw_from', p_payload->>'from'),
    v_test_mode
  )
  on conflict (provider_id, external_call_id) do update
  set property_id = coalesce(excluded.property_id, public.voice_calls.property_id),
      lead_id = coalesce(excluded.lead_id, public.voice_calls.lead_id),
      number_assignment_id = coalesce(excluded.number_assignment_id, public.voice_calls.number_assignment_id),
      mapping_status = case when excluded.mapping_status = 'matched' then 'matched' else public.voice_calls.mapping_status end,
      status = excluded.status,
      answered_by = excluded.answered_by,
      pathway_id = excluded.pathway_id,
      pathway_version = excluded.pathway_version,
      voice_id = excluded.voice_id,
      started_at = excluded.started_at,
      duration_seconds = excluded.duration_seconds,
      summary = excluded.summary,
      transcript = excluded.transcript,
      recording_url = excluded.recording_url,
      analysis = excluded.analysis,
      variables = excluded.variables,
      metadata = public.voice_calls.metadata || excluded.metadata,
      test_mode = excluded.test_mode,
      updated_at = now()
  returning id into v_voice_call_id;

  if v_lead_id is not null and not exists (
    select 1 from public.lead_interactions li
    where li.provider_id = v_provider_id and li.source_event_id = v_call_id
  ) then
    insert into public.lead_interactions (
      lead_id, property_id, provider_id, source_event_id, conversation_id,
      interaction_type, channel, direction, status, summary, content,
      occurred_at, metadata
    ) values (
      v_lead_id, v_property_id, v_provider_id, v_call_id, v_call_id,
      'call', 'voice', v_direction, v_status, nullif(p_payload->>'summary', ''),
      nullif(p_payload->>'concatenated_transcript', ''), v_started_at,
      jsonb_build_object(
        'voice_call_id', v_voice_call_id,
        'answered_by', p_payload->>'answered_by',
        'pathway_id', p_payload->>'pathway_id',
        'voice_id', p_payload->>'voice_id',
        'test_mode', v_test_mode
      )
    );
  end if;

  update public.webhook_events
  set status = 'processed', processed_at = now()
  where id = v_event_id;

  return jsonb_build_object(
    'accepted', true,
    'voice_call_id', v_voice_call_id,
    'external_call_id', v_call_id,
    'property_id', v_property_id,
    'lead_id', v_lead_id,
    'mapping_status', v_mapping_status,
    'test_mode', v_test_mode
  );
exception when others then
  if v_event_id is not null then
    update public.webhook_events
    set status = 'failed', error_message = sqlerrm
    where id = v_event_id;
  end if;
  raise;
end;
$$;

revoke all on function public.record_bland_webhook_attempt(jsonb, text, text, text, text, text) from public;
revoke all on function public.get_bland_voice_context(text, text, uuid, text) from public;
revoke all on function public.ingest_bland_call(jsonb, text, text) from public;

grant execute on function public.record_bland_webhook_attempt(jsonb, text, text, text, text, text) to anon, service_role;
grant execute on function public.get_bland_voice_context(text, text, uuid, text) to anon, service_role;
grant execute on function public.ingest_bland_call(jsonb, text, text) to anon, service_role;

comment on table public.voice_number_assignments is
'Phone-to-property routing inventory. Conflicted numbers cannot be activated, preventing a call from loading the wrong company.';
comment on table public.voice_calls is
'Normalized Bland.ai call ledger linked to the property and lead when deterministic routing information is available.';
comment on function public.get_bland_voice_context(text, text, uuid, text) is
'Returns the per-company brand, services, service area, availability, voice settings, and optional lead context for a shared Bland pathway.';
comment on function public.ingest_bland_call(jsonb, text, text) is
'Idempotently stores a Bland.ai call, resolves it to a company, and creates or enriches a test-safe lead and voice interaction when sufficient data exists.';
