create table if not exists public.callrail_tracker_inventory (
  id bigint generated by default as identity primary key,
  account_id text not null,
  account_name text,
  tracker_id text not null unique,
  tracker_name text not null,
  tracker_type text,
  tracker_status text,
  company_id text,
  company_name text,
  destination_phone_e164 text,
  tracking_numbers text[] not null default array[]::text[],
  sms_enabled boolean,
  call_flow jsonb not null default '{}'::jsonb check (jsonb_typeof(call_flow) = 'object'),
  source_config jsonb not null default '{}'::jsonb check (jsonb_typeof(source_config) = 'object'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists callrail_tracker_inventory_account_status_idx
  on public.callrail_tracker_inventory(account_id, tracker_status);
create index if not exists callrail_tracker_inventory_company_id_idx
  on public.callrail_tracker_inventory(company_id) where company_id is not null;
create index if not exists callrail_tracker_inventory_tracking_numbers_idx
  on public.callrail_tracker_inventory using gin(tracking_numbers);

alter table public.callrail_tracker_inventory enable row level security;
revoke all on public.callrail_tracker_inventory from anon, authenticated;

create or replace function public.sync_callrail_tracker_inventory(
  p_trackers jsonb,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_provider_id bigint;
  v_tracker jsonb;
  v_tracker_id text;
  v_phone_value jsonb;
  v_phone text;
  v_numbers text[];
  v_assignment_count integer;
  v_property_id bigint;
  v_trackers_upserted integer := 0;
  v_numbers_seen integer := 0;
  v_numbers_matched integer := 0;
  v_numbers_unmatched integer := 0;
  v_number_conflicts integer := 0;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'bland_ingest';

  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized inventory request' using errcode = '28000';
  end if;
  if jsonb_typeof(p_trackers) <> 'array' then
    raise exception 'trackers must be an array' using errcode = '22023';
  end if;

  select id into v_provider_id
  from public.integration_providers
  where provider_key = 'callrail' and is_active;
  if v_provider_id is null then
    raise exception 'CallRail provider not configured' using errcode = 'P0002';
  end if;

  for v_tracker in select value from jsonb_array_elements(p_trackers)
  loop
    v_tracker_id := nullif(v_tracker->>'id', '');
    if v_tracker_id is null then
      continue;
    end if;

    select coalesce(array_agg(phone order by phone), array[]::text[])
    into v_numbers
    from (
      select distinct private.normalize_e164(value #>> '{}') as phone
      from jsonb_array_elements(coalesce(v_tracker->'tracking_numbers', '[]'::jsonb))
    ) normalized
    where phone is not null;

    insert into public.callrail_tracker_inventory (
      account_id, account_name, tracker_id, tracker_name, tracker_type, tracker_status,
      company_id, company_name, destination_phone_e164, tracking_numbers, sms_enabled,
      call_flow, source_config, metadata, last_seen_at
    ) values (
      coalesce(nullif(v_tracker->>'account_id', ''), 'unknown'),
      nullif(v_tracker->>'account_name', ''),
      v_tracker_id,
      coalesce(nullif(v_tracker->>'name', ''), v_tracker_id),
      nullif(v_tracker->>'type', ''),
      nullif(v_tracker->>'status', ''),
      nullif(v_tracker#>>'{company,id}', ''),
      nullif(v_tracker#>>'{company,name}', ''),
      private.normalize_e164(coalesce(v_tracker->>'destination_number', v_tracker#>>'{call_flow,destination_number}')),
      v_numbers,
      nullif(v_tracker->>'sms_enabled', '')::boolean,
      case when jsonb_typeof(v_tracker->'call_flow') = 'object' then v_tracker->'call_flow' else '{}'::jsonb end,
      case when jsonb_typeof(v_tracker->'source') = 'object' then v_tracker->'source' else '{}'::jsonb end,
      jsonb_build_object('disabled_at', v_tracker->>'disabled_at', 'created_at', v_tracker->>'created_at'),
      now()
    )
    on conflict (tracker_id) do update
    set account_id = excluded.account_id,
        account_name = excluded.account_name,
        tracker_name = excluded.tracker_name,
        tracker_type = excluded.tracker_type,
        tracker_status = excluded.tracker_status,
        company_id = excluded.company_id,
        company_name = excluded.company_name,
        destination_phone_e164 = excluded.destination_phone_e164,
        tracking_numbers = excluded.tracking_numbers,
        sms_enabled = excluded.sms_enabled,
        call_flow = excluded.call_flow,
        source_config = excluded.source_config,
        metadata = public.callrail_tracker_inventory.metadata || excluded.metadata,
        last_seen_at = now(),
        updated_at = now();

    v_trackers_upserted := v_trackers_upserted + 1;

    foreach v_phone in array v_numbers
    loop
      v_numbers_seen := v_numbers_seen + 1;

      select count(*), min(property_id)
      into v_assignment_count, v_property_id
      from public.voice_number_assignments
      where phone_e164 = v_phone
        and number_role in ('website', 'tracking', 'inbound');

      if v_assignment_count = 0 then
        v_numbers_unmatched := v_numbers_unmatched + 1;
      elsif v_assignment_count > 1 then
        v_number_conflicts := v_number_conflicts + 1;
        update public.voice_number_assignments
        set provider_id = v_provider_id,
            external_number_id = v_tracker_id,
            routing_status = 'conflict',
            mapping_source = 'callrail_api',
            confidence = 0.500,
            metadata = metadata || jsonb_build_object(
              'callrail_account_id', v_tracker->>'account_id',
              'callrail_company_id', v_tracker#>>'{company,id}',
              'callrail_company_name', v_tracker#>>'{company,name}',
              'callrail_tracker_id', v_tracker_id,
              'callrail_tracker_name', v_tracker->>'name',
              'provider_verified_at', now()
            ),
            updated_at = now()
        where phone_e164 = v_phone;
      else
        v_numbers_matched := v_numbers_matched + 1;
        update public.voice_number_assignments
        set provider_id = v_provider_id,
            external_number_id = v_tracker_id,
            mapping_source = 'callrail_api',
            confidence = 1.000,
            metadata = metadata || jsonb_build_object(
              'callrail_account_id', v_tracker->>'account_id',
              'callrail_company_id', v_tracker#>>'{company,id}',
              'callrail_company_name', v_tracker#>>'{company,name}',
              'callrail_tracker_id', v_tracker_id,
              'callrail_tracker_name', v_tracker->>'name',
              'callrail_destination_number', coalesce(v_tracker->>'destination_number', v_tracker#>>'{call_flow,destination_number}'),
              'provider_verified_at', now()
            ),
            updated_at = now()
        where phone_e164 = v_phone and property_id = v_property_id;

        insert into public.source_mappings (
          platform, external_type, external_id, external_name,
          property_id, client_id, market_id, is_active, metadata
        )
        select 'CallRail', 'Tracker Number', v_tracker_id || ':' || v_phone,
               coalesce(nullif(v_tracker->>'name', ''), v_tracker_id),
               p.id, p.client_id, p.market_id, coalesce(v_tracker->>'status', 'active') = 'active',
               jsonb_build_object(
                 'tracker_id', v_tracker_id,
                 'tracking_phone_number', v_phone,
                 'company_id', v_tracker#>>'{company,id}',
                 'company_name', v_tracker#>>'{company,name}'
               )
        from public.properties p
        where p.id = v_property_id
        on conflict (platform, external_type, external_id) do update
        set external_name = excluded.external_name,
            property_id = excluded.property_id,
            client_id = excluded.client_id,
            market_id = excluded.market_id,
            is_active = excluded.is_active,
            metadata = public.source_mappings.metadata || excluded.metadata,
            updated_at = now();
      end if;
    end loop;
  end loop;

  return jsonb_build_object(
    'trackers_upserted', v_trackers_upserted,
    'numbers_seen', v_numbers_seen,
    'numbers_matched', v_numbers_matched,
    'numbers_unmatched', v_numbers_unmatched,
    'number_conflicts', v_number_conflicts
  );
end;
$$;

revoke all on function public.sync_callrail_tracker_inventory(jsonb, text) from public;
grant execute on function public.sync_callrail_tracker_inventory(jsonb, text) to anon, service_role;

comment on table public.callrail_tracker_inventory is
'Latest read-only inventory of CallRail companies, trackers, destination numbers, and tracking numbers used to verify website phone ownership.';
comment on function public.sync_callrail_tracker_inventory(jsonb, text) is
'Authenticated CallRail tracker upsert that verifies phone providers and maps unambiguous tracking numbers to LLG properties without activating Bland routing.';
