create schema if not exists private;

create table if not exists private.integration_secrets (
  secret_key text primary key,
  secret_hash bytea not null,
  updated_at timestamptz not null default now()
);

revoke all on schema private from public, anon, authenticated;
revoke all on all tables in schema private from public, anon, authenticated;

create table if not exists public.form_templates (
  id bigint generated by default as identity primary key,
  template_key text not null unique,
  provider_key text not null default 'fillout',
  fillout_form_id text unique,
  service_id bigint not null references public.services(id) on delete restrict,
  name text not null,
  status text not null default 'draft' check (status in ('draft', 'testing', 'active', 'paused', 'retired')),
  schema_version integer not null default 1 check (schema_version > 0),
  qualification_schema jsonb not null default '[]'::jsonb check (jsonb_typeof(qualification_schema) = 'array'),
  attribution_parameters text[] not null default array[]::text[],
  webhook_enabled boolean not null default false,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists form_templates_service_id_idx on public.form_templates(service_id);

create table if not exists public.property_form_templates (
  property_id bigint not null references public.properties(id) on delete cascade,
  form_template_id bigint not null references public.form_templates(id) on delete cascade,
  is_primary boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (property_id, form_template_id)
);

create index if not exists property_form_templates_form_template_id_idx on public.property_form_templates(form_template_id);

alter table public.form_templates enable row level security;
alter table public.property_form_templates enable row level security;

insert into public.services (slug, name, category, is_active)
values
  ('drainage', 'Drainage & French Drains', 'Exterior Water Management', true),
  ('retaining-walls', 'Retaining Walls', 'Hardscaping', true),
  ('concrete-pavers', 'Concrete & Pavers', 'Hardscaping', true),
  ('crawlspace', 'Crawlspace Services', 'Foundation & Waterproofing', true),
  ('decks-patios', 'Decks, Patios & Outdoor Living', 'Outdoor Living', true),
  ('fencing', 'Fencing', 'Exterior Construction', true),
  ('landscaping-lawn', 'Landscaping, Lawn & Irrigation', 'Landscaping', true),
  ('tree-land-clearing', 'Tree Service & Land Clearing', 'Tree & Land', true),
  ('bathroom-remodeling', 'Bathroom Remodeling', 'Interior Remodeling', true),
  ('pool-service', 'Pool Service', 'Pool', true),
  ('hvac', 'Heating & Cooling', 'HVAC', true),
  ('gutter-cleaning', 'Gutter Cleaning & Repair', 'Exterior Maintenance', true),
  ('painting', 'Painting', 'Painting', true),
  ('handyman', 'Handyman Services', 'Home Services', true),
  ('junk-removal', 'Junk Removal', 'Home Services', true),
  ('hurricane-services', 'Hurricane Preparation & Recovery', 'Storm Services', true),
  ('home-watch', 'Home Watch', 'Property Management', true),
  ('foundation-repair', 'Foundation Repair', 'Foundation & Waterproofing', true)
on conflict (slug) do update
set name = excluded.name,
    category = excluded.category,
    is_active = true,
    updated_at = now();

with classified as (
  select p.id as property_id,
    case
      when lower(p.name) like '%drain%' then 'drainage'
      when lower(p.name) ~ '(retaining|precisionwall|precisionwalls)' then 'retaining-walls'
      when lower(p.name) ~ '(concrete|paver)' then 'concrete-pavers'
      when lower(p.name) like '%crawlspace%' then 'crawlspace'
      when lower(p.name) ~ '(deck|patio|backyard|outdoorcontractor)' then 'decks-patios'
      when lower(p.name) like '%fence%' or lower(p.name) like '%fencing%' then 'fencing'
      when lower(p.name) ~ '(landscap|lawncare|sprinkler)' then 'landscaping-lawn'
      when lower(p.name) ~ '(treeservice|landclearing)' then 'tree-land-clearing'
      when lower(p.name) like '%bathroomremodel%' then 'bathroom-remodeling'
      when lower(p.name) like '%pool%' then 'pool-service'
      when lower(p.name) like '%keepitcool%' then 'hvac'
      when lower(p.name) like '%gutter%' then 'gutter-cleaning'
      when lower(p.name) like '%painting%' then 'painting'
      when lower(p.name) like '%handyman%' then 'handyman'
      when lower(p.name) like '%junkremoval%' then 'junk-removal'
      when lower(p.name) like '%hurricane%' then 'hurricane-services'
      when lower(p.name) like '%homewatch%' then 'home-watch'
      when lower(p.name) like '%foundation%' then 'foundation-repair'
      else null
    end as service_slug
  from public.properties p
  where p.domain is not null or p.website_url is not null
), mapped as (
  select c.property_id, s.id as service_id, s.name as service_name, c.service_slug
  from classified c
  join public.services s on s.slug = c.service_slug
  where c.service_slug is not null
)
insert into public.property_services (
  property_id, service_id, is_primary, public_name, is_active, accepting_leads,
  sort_order, qualification_mode, metadata
)
select property_id, service_id, true, service_name, true, true, 10, 'required',
  jsonb_build_object('classification', 'domain_name_v1', 'service_slug', service_slug)
from mapped
on conflict (property_id, service_id) do nothing;

with templates(template_key, service_slug, name) as (
  values
    ('drainage', 'drainage', 'LLG Template — Drainage & French Drains'),
    ('retaining-walls', 'retaining-walls', 'LLG Template — Retaining Walls'),
    ('concrete-pavers', 'concrete-pavers', 'LLG Template — Concrete & Pavers'),
    ('crawlspace', 'crawlspace', 'LLG Template — Crawlspace Services'),
    ('decks-patios', 'decks-patios', 'LLG Template — Decks, Patios & Outdoor Living'),
    ('fencing', 'fencing', 'LLG Template — Fencing'),
    ('landscaping-lawn', 'landscaping-lawn', 'LLG Template — Landscaping, Lawn & Irrigation'),
    ('tree-land-clearing', 'tree-land-clearing', 'LLG Template — Tree Service & Land Clearing'),
    ('bathroom-remodeling', 'bathroom-remodeling', 'LLG Template — Bathroom Remodeling'),
    ('pool-service', 'pool-service', 'LLG Template — Pool Service'),
    ('hvac', 'hvac', 'LLG Template — Heating & Cooling'),
    ('gutter-cleaning', 'gutter-cleaning', 'LLG Template — Gutter Cleaning & Repair'),
    ('painting', 'painting', 'LLG Template — Painting'),
    ('handyman', 'handyman', 'LLG Template — Handyman Services'),
    ('junk-removal', 'junk-removal', 'LLG Template — Junk Removal'),
    ('hurricane-services', 'hurricane-services', 'LLG Template — Hurricane Preparation & Recovery'),
    ('home-watch', 'home-watch', 'LLG Template — Home Watch'),
    ('foundation-repair', 'foundation-repair', 'LLG Template — Foundation Repair')
), params as (
  select array[
    'site_key','utm_source','utm_medium','utm_campaign','utm_content','utm_term','utm_id',
    'campaign_id','campaign_name','ad_group_id','ad_group_name','ad_id','ad_name','keyword','match_type',
    'gclid','gbraid','wbraid','fbclid','msclkid','rdt_cid','ttclid','li_fat_id',
    'landing_page_url','referrer_url','visitor_id','session_id','clarity_session_id'
  ]::text[] as names
)
insert into public.form_templates (
  template_key, service_id, name, attribution_parameters, metadata
)
select t.template_key, s.id, t.name, p.names,
  jsonb_build_object('spec_source', 'src/fillout-schema.ts', 'delivery_mode', 'test_only')
from templates t
join public.services s on s.slug = t.service_slug
cross join params p
on conflict (template_key) do update
set service_id = excluded.service_id,
    name = excluded.name,
    attribution_parameters = excluded.attribution_parameters,
    metadata = public.form_templates.metadata || excluded.metadata,
    updated_at = now();

insert into public.property_form_templates (property_id, form_template_id, is_primary, is_active, metadata)
select ps.property_id, ft.id, ps.is_primary, true,
  jsonb_build_object('assignment_source', 'property_service_v1')
from public.property_services ps
join public.form_templates ft on ft.service_id = ps.service_id
where ps.is_active
on conflict (property_id, form_template_id) do update
set is_primary = excluded.is_primary,
    is_active = true,
    updated_at = now();

insert into public.qualification_questions (
  question_key, default_prompt, answer_type, default_options, is_sensitive, is_active
)
values
  ('project_type', 'What type of project do you need help with?', 'multi_select', '[]'::jsonb, false, true),
  ('property_ownership', 'Do you own the property?', 'single_select', '["Yes","No","In the process of buying"]'::jsonb, false, true),
  ('project_timeline', 'When would you like the work completed?', 'single_select', '["As soon as possible","Within 30 days","1–3 months","3+ months","Just researching"]'::jsonb, false, true),
  ('budget_range', 'What is your estimated budget?', 'single_select', '["Under $5,000","$5,000–$10,000","$10,001–$25,000","$25,001–$50,000","Over $50,000","Not sure"]'::jsonb, false, true)
on conflict (question_key) do update
set default_prompt = excluded.default_prompt,
    answer_type = excluded.answer_type,
    default_options = excluded.default_options,
    is_active = true,
    updated_at = now();

insert into public.property_service_questions (
  property_id, service_id, question_id, display_prompt, is_required, is_active,
  sort_order, options_override, qualification_rule
)
select ps.property_id, ps.service_id, q.id, null, true, true,
  case q.question_key when 'project_type' then 10 when 'property_ownership' then 80 when 'project_timeline' then 90 else 100 end,
  '[]'::jsonb,
  case q.question_key
    when 'property_ownership' then '{"qualify_if":["Yes","In the process of buying"],"review_if":["No"]}'::jsonb
    when 'project_timeline' then '{"priority_values":["As soon as possible","Within 30 days"]}'::jsonb
    else '{}'::jsonb
  end
from public.property_services ps
cross join public.qualification_questions q
where ps.is_active
  and q.question_key in ('project_type', 'property_ownership', 'project_timeline', 'budget_range')
on conflict (property_id, service_id, question_id) do update
set is_active = true,
    updated_at = now();

create or replace function public.ingest_fillout_submission(
  p_form_id text,
  p_submission jsonb,
  p_payload jsonb,
  p_request_id text,
  p_ingest_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_expected_hash bytea;
  v_submission_id text;
  v_property_key text;
  v_property_id bigint;
  v_service_id bigint;
  v_client_id bigint;
  v_market_id bigint;
  v_test_mode boolean;
  v_event_id bigint;
  v_lead_id bigint;
  v_lead_public_id uuid;
  v_provider_id bigint;
  v_answer record;
  v_question_mapping_id bigint;
  v_source_category text;
begin
  select secret_hash into v_expected_hash
  from private.integration_secrets
  where secret_key = 'fillout_ingest';

  if v_expected_hash is null
    or extensions.digest(coalesce(p_ingest_token, ''), 'sha256') <> v_expected_hash then
    raise exception 'unauthorized intake request' using errcode = '28000';
  end if;

  if jsonb_typeof(p_submission) <> 'object' or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'invalid submission payload' using errcode = '22023';
  end if;

  v_submission_id := nullif(btrim(p_submission->>'submissionId'), '');
  v_property_key := nullif(btrim(p_submission->>'propertyKey'), '');
  if v_submission_id is null or v_property_key is null then
    raise exception 'missing submission identity' using errcode = '22023';
  end if;

  select sm.service_id
  into v_service_id
  from public.source_mappings sm
  where sm.platform = 'fillout'
    and sm.external_type = 'form_template'
    and sm.external_id = p_form_id
    and sm.is_active
    and sm.service_id is not null;

  if v_service_id is null then
    raise exception 'unmapped fillout form' using errcode = 'P0002';
  end if;

  select p.id, p.client_id, p.market_id, coalesce(pc.test_mode, true)
  into v_property_id, v_client_id, v_market_id, v_test_mode
  from public.properties p
  left join public.property_configurations pc on pc.property_id = p.id
  where p.property_key = v_property_key;

  if v_property_id is null then
    raise exception 'unknown property key' using errcode = 'P0002';
  end if;

  if not exists (
    select 1
    from public.property_services ps
    where ps.property_id = v_property_id
      and ps.service_id = v_service_id
      and ps.is_active
      and ps.accepting_leads
  ) then
    raise exception 'form does not match property service' using errcode = '22023';
  end if;

  insert into public.webhook_events (
    source_system, event_id, event_type, status, payload, received_at, attempt_count
  )
  values (
    'fillout', v_submission_id, 'form_submission', 'processing', p_payload, now(), 1
  )
  on conflict (source_system, event_id) do nothing
  returning id into v_event_id;

  if v_event_id is null then
    select l.id, l.public_id, l.property_id, l.service_id
    into v_lead_id, v_lead_public_id, v_property_id, v_service_id
    from public.leads l
    where l.source_system = 'fillout' and l.source_record_id = v_submission_id;

    if v_lead_id is null then
      raise exception 'duplicate event has no lead' using errcode = 'P0002';
    end if;

    return jsonb_build_object(
      'accepted', true,
      'duplicate', true,
      'lead_id', v_lead_id,
      'lead_public_id', v_lead_public_id,
      'property_id', v_property_id,
      'service_id', v_service_id,
      'test_mode', v_test_mode
    );
  end if;

  v_source_category := case
    when p_submission#>>'{attribution,source_category}' in ('paid','organic','referral','direct','partner','offline','unknown')
      then p_submission#>>'{attribution,source_category}'
    else 'unknown'
  end;

  insert into public.leads (
    ingestion_key, source_system, source_record_id, source_event_id,
    property_id, market_id, service_id, received_at, occurred_at,
    first_name, last_name, full_name, phone, normalized_phone, email, normalized_email,
    address_line_1, address_line_2, city, state_region, postal_code,
    lead_source, source_category, communication_channel, conversion_source,
    utm_source, utm_medium, utm_campaign, utm_content, utm_term, utm_id,
    campaign_id, campaign_name, ad_group_id, ad_group_name, ad_id, ad_name,
    keyword, match_type, gclid, gbraid, wbraid, fbclid, msclkid, rdt_cid, ttclid, li_fat_id,
    landing_page_url, referrer_url, visitor_id, session_id, clarity_session_id,
    fillout_submission_id, status, qualification_status, is_billable,
    consent_to_contact, consent_text, metadata
  ) values (
    'fillout:' || v_submission_id, 'fillout', v_submission_id, v_event_id,
    v_property_id, v_market_id, v_service_id, now(),
    coalesce((p_submission->>'submissionTime')::timestamptz, now()),
    nullif(p_submission->>'firstName',''), nullif(p_submission->>'lastName',''), nullif(p_submission->>'fullName',''),
    nullif(p_submission->>'phone',''), nullif(p_submission->>'phone',''),
    nullif(lower(p_submission->>'email'),''), nullif(lower(p_submission->>'email'),''),
    nullif(p_submission->>'addressLine1',''), nullif(p_submission->>'addressLine2',''),
    nullif(p_submission->>'city',''), nullif(p_submission->>'stateRegion',''), nullif(p_submission->>'postalCode',''),
    coalesce(nullif(p_submission#>>'{attribution,utm_source}',''), 'Website Form'),
    v_source_category, 'website_form', 'Fillout',
    nullif(p_submission#>>'{attribution,utm_source}',''), nullif(p_submission#>>'{attribution,utm_medium}',''),
    nullif(p_submission#>>'{attribution,utm_campaign}',''), nullif(p_submission#>>'{attribution,utm_content}',''),
    nullif(p_submission#>>'{attribution,utm_term}',''), nullif(p_submission#>>'{attribution,utm_id}',''),
    nullif(p_submission#>>'{attribution,campaign_id}',''), nullif(p_submission#>>'{attribution,campaign_name}',''),
    nullif(p_submission#>>'{attribution,ad_group_id}',''), nullif(p_submission#>>'{attribution,ad_group_name}',''),
    nullif(p_submission#>>'{attribution,ad_id}',''), nullif(p_submission#>>'{attribution,ad_name}',''),
    nullif(p_submission#>>'{attribution,keyword}',''), nullif(p_submission#>>'{attribution,match_type}',''),
    nullif(p_submission#>>'{attribution,gclid}',''), nullif(p_submission#>>'{attribution,gbraid}',''),
    nullif(p_submission#>>'{attribution,wbraid}',''), nullif(p_submission#>>'{attribution,fbclid}',''),
    nullif(p_submission#>>'{attribution,msclkid}',''), nullif(p_submission#>>'{attribution,rdt_cid}',''),
    nullif(p_submission#>>'{attribution,ttclid}',''), nullif(p_submission#>>'{attribution,li_fat_id}',''),
    nullif(p_submission#>>'{attribution,landing_page_url}',''), nullif(p_submission#>>'{attribution,referrer_url}',''),
    nullif(p_submission#>>'{attribution,visitor_id}',''), nullif(p_submission#>>'{attribution,session_id}',''),
    nullif(p_submission#>>'{attribution,clarity_session_id}',''),
    v_submission_id,
    case when v_test_mode then 'validating' else 'new' end,
    case when v_test_mode then 'needs_review' else 'unreviewed' end,
    case when v_test_mode then false else null end,
    coalesce((p_submission->>'consentGranted')::boolean, false),
    nullif(p_submission->>'consentText',''),
    jsonb_build_object(
      'request_id', p_request_id,
      'test_mode', v_test_mode,
      'fillout_form_id', p_form_id,
      'consent_version', p_submission->>'consentVersion',
      'message', p_submission->>'message',
      'answers', coalesce(p_submission->'answers', '{}'::jsonb),
      'questions', coalesce(p_submission->'questions', '[]'::jsonb),
      'url_parameters', coalesce(p_submission->'urlParameters', '[]'::jsonb)
    )
  )
  returning id, public_id into v_lead_id, v_lead_public_id;

  select ip.id into v_provider_id
  from public.integration_providers ip
  where ip.provider_key = 'fillout' and ip.is_active;

  insert into public.lead_interactions (
    lead_id, property_id, provider_id, source_event_id, interaction_type,
    channel, direction, status, summary, content, occurred_at, metadata
  ) values (
    v_lead_id, v_property_id, v_provider_id, v_submission_id, 'form_submission',
    'web', 'inbound', 'received', 'Website quote request submitted',
    nullif(p_submission->>'message',''),
    coalesce((p_submission->>'submissionTime')::timestamptz, now()),
    jsonb_build_object('fillout_form_id', p_form_id, 'request_id', p_request_id, 'test_mode', v_test_mode)
  );

  insert into public.lead_consent_events (
    lead_id, property_id, consent_type, consent_status, disclosure_text,
    capture_source, occurred_at, metadata
  ) values (
    v_lead_id, v_property_id, 'contact',
    case when coalesce((p_submission->>'consentGranted')::boolean, false) then 'granted' else 'denied' end,
    nullif(p_submission->>'consentText',''), 'fillout',
    coalesce((p_submission->>'submissionTime')::timestamptz, now()),
    jsonb_build_object('consent_version', p_submission->>'consentVersion', 'fillout_submission_id', v_submission_id)
  );

  if jsonb_typeof(p_submission->'answers') = 'object' then
    for v_answer in select key, value from jsonb_each(p_submission->'answers')
    loop
      select psq.id into v_question_mapping_id
      from public.property_service_questions psq
      join public.qualification_questions q on q.id = psq.question_id
      where psq.property_id = v_property_id
        and psq.service_id = v_service_id
        and psq.is_active
        and q.question_key = v_answer.key;

      if v_question_mapping_id is not null then
        insert into public.lead_qualification_answers (
          lead_id, property_service_question_id, answer_text, answer_number,
          answer_boolean, answer_json, answered_via, metadata
        ) values (
          v_lead_id,
          v_question_mapping_id,
          case when jsonb_typeof(v_answer.value) = 'string' then v_answer.value #>> '{}' else null end,
          case when jsonb_typeof(v_answer.value) = 'number' then (v_answer.value #>> '{}')::numeric else null end,
          case when jsonb_typeof(v_answer.value) = 'boolean' then (v_answer.value #>> '{}')::boolean else null end,
          v_answer.value,
          'form',
          jsonb_build_object('fillout_form_id', p_form_id, 'fillout_submission_id', v_submission_id)
        );
      end if;
    end loop;
  end if;

  update public.webhook_events
  set status = 'processed', processed_at = now()
  where id = v_event_id;

  return jsonb_build_object(
    'accepted', true,
    'duplicate', false,
    'lead_id', v_lead_id,
    'lead_public_id', v_lead_public_id,
    'property_id', v_property_id,
    'service_id', v_service_id,
    'test_mode', v_test_mode
  );
end;
$$;

revoke all on function public.ingest_fillout_submission(text, jsonb, jsonb, text, text) from public;
grant execute on function public.ingest_fillout_submission(text, jsonb, jsonb, text, text) to anon, service_role;

comment on function public.ingest_fillout_submission(text, jsonb, jsonb, text, text)
is 'Authenticated server-side intake for reusable Fillout templates. Validates form-to-service and site-to-service mappings, writes an idempotent test-safe lead, and records consent and qualification answers.';
